// This snippet file was generated by processing the source file:
// ./database-next/lists-of-data.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START rtdb_social_push_modular]
import { getDatabase, ref, push, set } from "firebase/database";

// Create a new post reference with an auto-generated id
const db = getDatabase();
const postListRef = ref(db, 'posts');
const newPostRef = push(postListRef);
set(newPostRef, {
    // ...
});
// [END rtdb_social_push_modular]