// This snippet file was generated by processing the source file:
// ./auth-next/cordova.js
//
// To make edits to the snippets in this file, please edit the source

// [START auth_create_google_provider_modular]
import { GoogleAuthProvider } from "firebase/auth";

const provider = new GoogleAuthProvider();
// [END auth_create_google_provider_modular]