// This snippet file was generated by processing the source file:
// ./auth-react/facebook.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START auth_facebook_signin_popup_react]
import { getAuth, signInWithPopup, FacebookAuthProvider } from "firebase/auth";

function SignInButton() {
  async function signIn() {
    const auth = getAuth();
    try {
      const result = await signInWithPopup(auth, provider);
      // The signed-in user info.
      const user = result.user;

      // This gives you a Facebook Access Token. You can use it to access the Facebook API.
      const credential = FacebookAuthProvider.credentialFromResult(result);
      const accessToken = credential.accessToken;

      // IdP data available using getAdditionalUserInfo(result)
      // ...
    } catch (error) {
      // Handle Errors here.
      const errorCode = error.code;
      const errorMessage = error.message;
      // The email of the user's account used.
      const email = error.customData.email;
      // The AuthCredential type that was used.
      const credential = FacebookAuthProvider.credentialFromError(error);

      // ...
    }
  }

  return <button onClick={signIn}>Sign in with Facebook</button>;
}
// [END auth_facebook_signin_popup_react]