// This snippet file was generated by processing the source file:
// ./auth-react/facebook.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START auth_facebook_provider_create_react]
import { FacebookAuthProvider } from "firebase/auth";

const provider = new FacebookAuthProvider();
// [END auth_facebook_provider_create_react]