// This snippet file was generated by processing the source file:
// ./auth-react/facebook.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START auth_facebook_provider_credential_react]
import { FacebookAuthProvider } from "firebase/auth";

const credential = FacebookAuthProvider.credential(accessToken);
// [END auth_facebook_provider_credential_react]