// This snippet file was generated by processing the source file:
// ./auth-next/microsoft-oauth.js
//
// To make edits to the snippets in this file, please edit the source

// [START auth_msft_link_popup_modular]
import { getAuth, linkWithPopup, OAuthProvider } from "firebase/auth";

const provider = new OAuthProvider('microsoft.com');
const auth = getAuth();

linkWithPopup(auth.currentUser, provider)
    .then((result) => {
      // Microsoft credential is linked to the current user.
      // IdP data available in result.additionalUserInfo.profile.
      // OAuth access token can also be retrieved:
      // result.credential.accessToken
      // OAuth ID token can also be retrieved:
      // result.credential.idToken
    })
    .catch((error) => {
      // Handle error.
    });
// [END auth_msft_link_popup_modular]