// This snippet file was generated by processing the source file:
// ./auth-next/microsoft-oauth.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START auth_msft_provider_params_modular]
provider.setCustomParameters({
  // Force re-consent.
  prompt: 'consent',
  // Target specific email with login hint.
  login_hint: 'user@firstadd.onmicrosoft.com'
});
// [END auth_msft_provider_params_modular]