// This snippet file was generated by processing the source file:
// ./auth-next/microsoft-oauth.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START auth_msft_create_provider_modular]
import { OAuthProvider } from "firebase/auth";

const provider = new OAuthProvider('microsoft.com');
// [END auth_msft_create_provider_modular]