// This snippet file was generated by processing the source file:
// ./auth-next/microsoft-oauth.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START auth_msft_provider_params_tenant_modular]
provider.setCustomParameters({
  // Optional "tenant" parameter in case you are using an Azure AD tenant.
  // eg. '8eaef023-2b34-4da1-9baa-8bc8c9d6a490' or 'contoso.onmicrosoft.com'
  // or "common" for tenant-independent tokens.
  // The default value is "common".
  tenant: 'TENANT_ID'
});
// [END auth_msft_provider_params_tenant_modular]