// This snippet file was generated by processing the source file:
// ./auth-next/microsoft-oauth.js
//
// To make edits to the snippets in this file, please edit the source

// [START auth_msft_signin_popup_modular]
import { getAuth, signInWithPopup } from "firebase/auth";

const auth = getAuth();
signInWithPopup(auth, provider)
  .then((result) => {
    // User is signed in.
    // IdP data available in result.additionalUserInfo.profile.
    // OAuth access token can also be retrieved:
    // result.credential.accessToken
    // OAuth ID token can also be retrieved:
    // result.credential.idToken
  })
  .catch((error) => {
    // Handle error.
  });
// [END auth_msft_signin_popup_modular]