// This snippet file was generated by processing the source file:
// ./auth-next/microsoft-oauth.js
//
// To make edits to the snippets in this file, please edit the source

// [START auth_msft_link_popup_modular]
import { getAuth, linkWithPopup, OAuthProvider } from "firebase/auth";

const provider = new OAuthProvider('microsoft.com');
const auth = getAuth(firebaseApp);

linkWithPopup(auth.currentUser, provider)
    .then((result) => {
      // Microsoft credential is linked to the current user.
      // IdP data available in result.additionalUserInfo.profile.

      // Get the OAuth access token and ID Token
      const credential = OAuthProvider.credentialFromResult(result);
      const accessToken = credential.accessToken;
      const idToken = credential.idToken;
    })
    .catch((error) => {
      // Handle error.
    });
// [END auth_msft_link_popup_modular]