// This snippet file was generated by processing the source file:
// ./storage-react/create-reference.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START storage_create_ref_react]
import { getStorage, ref } from "firebase/storage";

// Get a reference to the storage service, which is used to create references in your storage bucket
const storage = getStorage();

// Create a storage reference from our storage service
const storageRef = ref(storage);
// [END storage_create_ref_react]