// This snippet file was generated by processing the source file:
// ./firestore-react/test.solution-bundles.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START fs_bundle_load_react]
import { useEffect, useState } from "react";
import { loadBundle, namedQuery, getDocsFromCache } from "firebase/firestore";

function LatestStories() {
  const [stories, setStories] = useState([]);

  useEffect(() => {
    async function fetchFromBundle() {
      // Fetch the bundle from Firebase Hosting, if the CDN cache is hit the 'X-Cache'
      // response header will be set to 'HIT'
      const resp = await fetch('/createBundle');

      // Load the bundle contents into the Firestore SDK
      await loadBundle(db, resp.body);

      // Query the results from the cache
      const query = await namedQuery(db, 'latest-stories-query');
      const storiesSnap = await getDocsFromCache(query);

      // Use the results
      setStories(storiesSnap.docs);
    }
    fetchFromBundle();
  }, []);

  return (
    <ul>
      {stories.map((doc) => (
        <li key={doc.id}>{doc.data().title}</li>
      ))}
    </ul>
  );
}
// [END fs_bundle_load_react]