// This snippet file was generated by processing the source file:
// ./database-next/offline.js
//
// To make edits to the snippets in this file, please edit the source

// [START rtdb_ondisconnect_simple_modular]
import { getDatabase } from "firebase/database";

const db = getDatabase(firebaseApp);
const presenceRef = db.ref("disconnectmessage");
// Write a string when this client loses connection
presenceRef.onDisconnect().set("I disconnected!");
// [END rtdb_ondisconnect_simple_modular]