// This snippet file was generated by processing the source file:
// ./database-next/offline.js
//
// To make edits to the snippets in this file, please edit the source

// [START rtdb_set_server_timestamp_modular]
import { getDatabase, ServerValue } from "firebase/database";

const db = getDatabase(firebaseApp);
const userLastOnlineRef = db.ref("users/joe/lastOnline");
userLastOnlineRef.onDisconnect().set(ServerValue.TIMESTAMP);
// [END rtdb_set_server_timestamp_modular]