// This snippet file was generated by processing the source file:
// ./database-next/offline.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START rtdb_set_server_timestamp_modular]
import { getDatabase, ref, onDisconnect, serverTimestamp } from "firebase/database";

const db = getDatabase();
const userLastOnlineRef = ref(db, "users/joe/lastOnline");
onDisconnect(userLastOnlineRef).set(serverTimestamp());
// [END rtdb_set_server_timestamp_modular]