// This snippet file was generated by processing the source file:
// ./auth-react/oidc.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START auth_oidc_signin_redirect_react]
import { useTransition } from "react";
import { getAuth, signInWithRedirect } from "firebase/auth";

function SignInButton() {
  const [isPending, startTransition] = useTransition();

  function signIn() {
    startTransition(async () => {
      const auth = getAuth();
      await signInWithRedirect(auth, provider);
    });
  }

  return <button onClick={signIn} disabled={isPending}>Sign in with OIDC</button>;
}
// [END auth_oidc_signin_redirect_react]