// This snippet file was generated by processing the source file:
// ./auth-react/oidc.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START auth_oidc_signin_popup_react]
import { useTransition } from "react";
import { getAuth, signInWithPopup, OAuthProvider } from "firebase/auth";

function SignInButton() {
  const [isPending, startTransition] = useTransition();

  function signIn() {
    startTransition(async () => {
      const auth = getAuth();
      try {
        const result = await signInWithPopup(auth, provider);
        // User is signed in.
        const credential = OAuthProvider.credentialFromResult(result);
        // This gives you an access token for the OIDC provider. You can use it to directly interact with that provider
      } catch (error) {
        // Handle Errors here.
        const errorCode = error.code;
        const errorMessage = error.message;
        // The email of the user's account used.
        const email = error.customData.email;
        // The AuthCredential type that was used.
        const credential = OAuthProvider.credentialFromError(error);
        // Handle / display error.
        // ...
      }
    });
  }

  return <button onClick={signIn} disabled={isPending}>Sign in with OIDC</button>;
}
// [END auth_oidc_signin_popup_react]