// This snippet file was generated by processing the source file:
// ./auth-next/email.js
//
// To make edits to the snippets in this file, please edit the source

// [START auth_signup_password_modular]
import { getAuth, createUserWithEmailAndPassword } from "firebase/auth";

const auth = getAuth(firebaseApp);
createUserWithEmailAndPassword(auth, email, password)
  .then((user) => {
    // Signed in 
    // ...
  })
  .catch((error) => {
    const errorCode = error.code;
    const errorMessage = error.message;
    // ..
  });
// [END auth_signup_password_modular]