// This snippet file was generated by processing the source file:
// ./storage-next/upload-files.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START storage_upload_ref_modular]
import { getStorage, ref } from "firebase/storage";

// Create a root reference
const storage = getStorage();

// Create a reference to 'mountains.jpg'
const mountainsRef = ref(storage, 'mountains.jpg');

// Create a reference to 'images/mountains.jpg'
const mountainImagesRef = ref(storage, 'images/mountains.jpg');

// While the file names are the same, the references point to different files
mountainsRef.name === mountainImagesRef.name;           // true
mountainsRef.fullPath === mountainImagesRef.fullPath;   // false 
// [END storage_upload_ref_modular]