// This snippet file was generated by processing the source file:
// ./storage-next/upload-files.js
//
// To make edits to the snippets in this file, please edit the source

// [START storage_upload_blob_modular]
import { getStorage, ref, uploadBytes } from "firebase/storage";

const storage = getStorage();
const storageRef = ref(storage, 'some-child');

// 'file' comes from the Blob or File API
uploadBytes(storageRef, file).then((snapshot) => {
  console.log('Uploaded a blob or file!');
});
// [END storage_upload_blob_modular]