// This snippet file was generated by processing the source file:
// ./perf-react/index.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START perf_import_react]
import { getPerformance } from "firebase/performance";
// [END perf_import_react]