// This snippet file was generated by processing the source file:
// ./perf-react/index.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START perf_initialize_app_react]
// TODO: Replace the following with your app's Firebase project configuration
// See: https://firebase.google.com/docs/web/learn-more#config-object
const firebaseConfig = {
  // ...
};

// Initialize Firebase
// Initialize Firebase once at module scope (e.g. src/firebase.js), not inside a component.
const app = initializeApp(firebaseConfig);
// [END perf_initialize_app_react]