// This snippet file was generated by processing the source file:
// ./auth-react/custom-email-handler.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START auth_handle_reset_password_react]
import { useEffect, useState, useActionState } from "react";
import { verifyPasswordResetCode, confirmPasswordReset } from "firebase/auth";

function ResetPasswordForm({ actionCode, continueUrl, lang }) {
  // Localize the UI to the selected language as determined by the lang
  // parameter.
  const [accountEmail, setAccountEmail] = useState(null);

  useEffect(() => {
    let ignore = false;
    // Verify the password reset code is valid.
    verifyPasswordResetCode(auth, actionCode).then((email) => {
      if (ignore) return;
      // Show the reset screen with the user's email and ask the user for
      // the new password.
      setAccountEmail(email);
    }).catch((error) => {
      // Invalid or expired action code. Ask user to try to reset the password
      // again.
    });
    // Ignore the result if actionCode changes before the read completes.
    return () => { ignore = true; };
  }, [actionCode]);

  const [error, resetPassword, isPending] = useActionState(async (previousError, formData) => {
    const newPassword = formData.get("newPassword");

    try {
      // Save the new password.
      await confirmPasswordReset(auth, actionCode, newPassword);
      // Password reset has been confirmed and new password updated.

      // TODO: Display a link back to the app, or sign-in the user directly
      // if the page belongs to the same domain as the app:
      // auth.signInWithEmailAndPassword(accountEmail, newPassword);

      // TODO: If a continue URL is available, display a button which on
      // click redirects the user back to the app via continueUrl with
      // additional state determined from that URL's parameters.
      return null;
    } catch (error) {
      // Error occurred during confirmation. The code might have expired or the
      // password is too weak.
      return error.message;
    }
  }, null);

  return accountEmail ? (
    <form action={resetPassword}>
      <p>{accountEmail}</p>
      <input name="newPassword" type="password" />
      <button type="submit" disabled={isPending}>Save</button>
      {error ? <p>{error}</p> : null}
    </form>
  ) : (
    <p>Loading...</p>
  );
}
// [END auth_handle_reset_password_react]