// This snippet file was generated by processing the source file:
// ./auth-react/custom-email-handler.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START auth_handle_recover_email_react]
import { useEffect, useState } from "react";
import { checkActionCode, applyActionCode, sendPasswordResetEmail } from "firebase/auth";

function EmailRecovery({ actionCode, lang }) {
  // Localize the UI to the selected language as determined by the lang
  // parameter.
  const [restoredEmail, setRestoredEmail] = useState(null);

  useEffect(() => {
    let ignore = false;
    let restoredEmail = null;
    // Confirm the action code is valid.
    checkActionCode(auth, actionCode).then((info) => {
      // Get the restored email address.
      restoredEmail = info['data']['email'];

      // Revert to the old email.
      return applyActionCode(auth, actionCode);
    }).then(() => {
      if (ignore) return;
      // Account email reverted to restoredEmail
      setRestoredEmail(restoredEmail);

      // You might also want to give the user the option to reset their password
      // in case the account was compromised:
      sendPasswordResetEmail(auth, restoredEmail).then(() => {
        // Password reset confirmation sent. Ask user to check their email.
      }).catch((error) => {
        // Error encountered while sending password reset code.
      });
    }).catch((error) => {
      // Invalid code.
    });
    // Ignore the result if actionCode changes before the read completes.
    return () => { ignore = true; };
  }, [actionCode]);

  // Display a confirmation message to the user.
  return restoredEmail ? <p>Account email reverted to {restoredEmail}</p> : <p>Loading...</p>;
}
// [END auth_handle_recover_email_react]