// This snippet file was generated by processing the source file:
// ./auth-react/custom-email-handler.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START auth_handle_mgmt_query_params_react]
import { initializeApp } from "firebase/app";
import { getAuth } from "firebase/auth";

// Configure the Firebase SDK.
// This is the minimum configuration required for the API to be used.
const config = {
  'apiKey': "YOUR_API_KEY" // Copy this key from the web initialization
                           // snippet found in the Firebase console.
};
// Initialize Firebase once at module scope (e.g. src/firebase.js), not inside a component.
const app = initializeApp(config);
const auth = getAuth(app);

function EmailActionHandler() {
  // TODO: Implement getParameterByName()

  // Get the action to complete.
  const mode = getParameterByName('mode');
  // Get the one-time code from the query parameter.
  const actionCode = getParameterByName('oobCode');
  // (Optional) Get the continue URL from the query parameter if available.
  const continueUrl = getParameterByName('continueUrl');
  // (Optional) Get the language code if available.
  const lang = getParameterByName('lang') || 'en';

  // Handle the user management action.
  switch (mode) {
    case 'resetPassword':
      // Display reset password handler and UI.
      return <ResetPasswordForm actionCode={actionCode} continueUrl={continueUrl} lang={lang} />;
    case 'recoverEmail':
      // Display email recovery handler and UI.
      return <EmailRecovery actionCode={actionCode} lang={lang} />;
    case 'verifyEmail':
      // Display email verification handler and UI.
      return <EmailVerification actionCode={actionCode} continueUrl={continueUrl} lang={lang} />;
    default:
      // Error: invalid mode.
      return null;
  }
}
// [END auth_handle_mgmt_query_params_react]