// This snippet file was generated by processing the source file:
// ./database-react/sharding.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START rtdb_multiple_instances_react]
import { initializeApp } from "firebase/app";
import { getDatabase } from "firebase/database";

// Initialize Firebase once at module scope (e.g. src/firebase.js), not inside a component.
const app1 = initializeApp({
  databaseURL: "https://testapp-1234-1.firebaseio.com"
});

const app2 = initializeApp({
  databaseURL: "https://testapp-1234-2.firebaseio.com"
}, 'app2');

// Get the default database instance for an app1
const database1 = getDatabase(app1);

// Get a database instance for app2
const database2 = getDatabase(app2);
// [END rtdb_multiple_instances_react]