// This snippet file was generated by processing the source file:
// ./analytics-next/index.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START analytics_log_event_modular]
import { getAnalytics, logEvent } from "firebase/analytics";

const analytics = getAnalytics();
logEvent(analytics, 'notification_received');
// [END analytics_log_event_modular]