// This snippet file was generated by processing the source file:
// ./analytics-next/index.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START analytics_record_screen_view_modular]
import { getAnalytics, logEvent } from "firebase/analytics";

const analytics = getAnalytics();
logEvent(analytics, 'screen_view', {
  firebase_screen: screenName, 
  firebase_screen_class: screenClass
});
// [END analytics_record_screen_view_modular]