// This snippet file was generated by processing the source file:
// ./auth-react/index.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START auth_signin_credential_react]
import { getAuth, signInWithCredential } from "firebase/auth";

function SignInButton() {
  async function signIn() {
    // Sign in with the credential from the user.
    const auth = getAuth();
    try {
      const result = await signInWithCredential(auth, credential);
      // Signed in
      // ...
    } catch (error) {
      // Handle Errors here.
      const errorCode = error.code;
      const errorMessage = error.message;
      // The email of the user's account used.
      const email = error.customData.email;
      // ...
    }
  }

  return <button onClick={signIn}>Sign in</button>;
}
// [END auth_signin_credential_react]