// This snippet file was generated by processing the source file:
// ./auth-react/index.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START auth_state_listener_react]
import { useEffect, useState } from "react";
import { getAuth, onAuthStateChanged } from "firebase/auth";

function AuthStatus() {
  const [user, setUser] = useState(null);

  useEffect(() => {
    const auth = getAuth();
    // onAuthStateChanged returns an unsubscribe function. Returning it from the
    // effect detaches the listener when the component unmounts.
    return onAuthStateChanged(auth, (user) => {
      setUser(user);
    });
  }, []);

  return user ? (
    // User is signed in, see docs for a list of available properties
    // https://firebase.google.com/docs/reference/js/auth.user
    <p>{user.uid}</p>
  ) : (
    // User is signed out
    <p>Signed out</p>
  );
}
// [END auth_state_listener_react]