// This snippet file was generated by processing the source file:
// ./auth-react/index.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START auth_sign_out_react]
import { useTransition } from "react";
import { getAuth, signOut } from "firebase/auth";

function SignOutButton() {
  const [isPending, startTransition] = useTransition();

  function handleSignOut() {
    startTransition(async () => {
      const auth = getAuth();
      try {
        await signOut(auth);
        // Sign-out successful.
      } catch (error) {
        // An error happened.
      }
    });
  }

  return <button onClick={handleSignOut} disabled={isPending}>Sign out</button>;
}
// [END auth_sign_out_react]