// This snippet file was generated by processing the source file:
// ./database-next/emulator-suite.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START rtdb_emulator_flush_modular]
import { getDatabase, ref, set } from "firebase/database";

// With a database Reference, write null to clear the database.
const db = getDatabase();
set(ref(db), null);
// [END rtdb_emulator_flush_modular]