// This snippet file was generated by processing the source file:
// ./functions-react/callable.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START fb_functions_call_add_message_react]
import { useActionState } from "react";
import { getFunctions, httpsCallable } from "firebase/functions";

function AddMessageForm() {
  const [sanitizedMessage, callAddMessage, isPending] = useActionState(async (previousMessage, formData) => {
    const functions = getFunctions();
    const addMessage = httpsCallable(functions, 'addMessage');
    const result = await addMessage({ text: formData.get("messageText") });
    // Read result of the Cloud Function.
    /** @type {any} */
    const data = result.data;
    const sanitizedMessage = data.text;
    return sanitizedMessage;
  }, null);

  return (
    <form action={callAddMessage}>
      <input name="messageText" />
      <button type="submit" disabled={isPending}>Send</button>
      {sanitizedMessage ? <p>{sanitizedMessage}</p> : null}
    </form>
  );
}
// [END fb_functions_call_add_message_react]