// This snippet file was generated by processing the source file:
// ./storage-react/upload-files.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START storage_manage_uploads_react]
import { useRef } from "react";
import { getStorage, ref, uploadBytesResumable } from "firebase/storage";

function UploadForm() {
  const uploadTask = useRef(null);

  function startUpload(formData) {
    const file = formData.get("file");
    const storage = getStorage();
    const storageRef = ref(storage, 'images/mountains.jpg');

    // Upload the file and metadata
    uploadTask.current = uploadBytesResumable(storageRef, file);
  }

  function pauseUpload() {
    // Pause the upload
    uploadTask.current.pause();
  }

  function resumeUpload() {
    // Resume the upload
    uploadTask.current.resume();
  }

  function cancelUpload() {
    // Cancel the upload
    uploadTask.current.cancel();
  }

  return (
    <form action={startUpload}>
      <input name="file" type="file" />
      <button type="submit">Upload</button>
      <button type="button" onClick={pauseUpload}>Pause</button>
      <button type="button" onClick={resumeUpload}>Resume</button>
      <button type="button" onClick={cancelUpload}>Cancel</button>
    </form>
  );
}
// [END storage_manage_uploads_react]