// This snippet file was generated by processing the source file:
// ./storage-react/upload-files.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START storage_upload_metadata_react]
import { getStorage, ref, uploadBytes } from "firebase/storage";

function UploadForm() {
  async function uploadMetadata(formData) {
    const file = formData.get("file");
    const storage = getStorage();
    const storageRef = ref(storage, 'images/mountains.jpg');

    // Create file metadata including the content type
    /** @type {any} */
    const metadata = {
      contentType: 'image/jpeg',
    };

    // Upload the file and metadata
    await uploadBytes(storageRef, file, metadata);
  }

  return (
    <form action={uploadMetadata}>
      <input name="file" type="file" />
      <button type="submit">Upload</button>
    </form>
  );
}
// [END storage_upload_metadata_react]