// This snippet file was generated by processing the source file:
// ./functions-react/emulator-suite.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START fb_functions_emulator_connect_react]
import { getApp } from "firebase/app";
import { getFunctions, connectFunctionsEmulator } from "firebase/functions";

const functions = getFunctions(getApp());
connectFunctionsEmulator(functions, "127.0.0.1", 5001);
// [END fb_functions_emulator_connect_react]