// This snippet file was generated by processing the source file:
// ./functions-react/emulator-suite.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START fb_functions_callable_call_react]
import { getApp } from "firebase/app";
import { getFunctions, httpsCallable } from "firebase/functions";

const functions = getFunctions(getApp());
const addMessage = httpsCallable(functions, 'addMessage');

const result = await addMessage({ text: '<message text>'});
/** @type {any} */
const data = result.data;
const sanitizedMessage = data.text;
// ...
// [END fb_functions_callable_call_react]