// This snippet file was generated by processing the source file:
// ./auth-react/cordova.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START auth_create_google_provider_react]
import { GoogleAuthProvider } from "firebase/auth/cordova";

const provider = new GoogleAuthProvider();
// [END auth_create_google_provider_react]