// This snippet file was generated by processing the source file:
// ./auth-react/custom.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START auth_sign_in_custom_react]
import { getAuth, signInWithCustomToken } from "firebase/auth";

function CustomTokenSignInButton({ token }) {
  async function signIn() {
    const auth = getAuth();
    try {
      const userCredential = await signInWithCustomToken(auth, token);
      // Signed in
      const user = userCredential.user;
      // ...
    } catch (error) {
      const errorCode = error.code;
      const errorMessage = error.message;
      // ...
    }
  }

  return <button onClick={signIn}>Sign in</button>;
}
// [END auth_sign_in_custom_react]