// This snippet file was generated by processing the source file:
// ./auth-next/firebaseui.js
//
// To make edits to the snippets in this file, please edit the source

// [START auth_fui_start_oauth_modular]
ui.start('#firebaseui-auth-container', {
  signInOptions: [
    // List of OAuth providers supported.
    firebase.auth.GoogleAuthProvider.PROVIDER_ID,
    firebase.auth.FacebookAuthProvider.PROVIDER_ID,
    firebase.auth.TwitterAuthProvider.PROVIDER_ID,
    firebase.auth.GithubAuthProvider.PROVIDER_ID
  ],
  // Other config options...
});  
// [END auth_fui_start_oauth_modular]