// This snippet file was generated by processing the source file:
// ./auth-next/firebaseui.js
//
// To make edits to the snippets in this file, please edit the source

// [START auth_fui_start_email_options_modular]
ui.start('#firebaseui-auth-container', {
  signInOptions: [
    {
      provider: firebase.auth.EmailAuthProvider.PROVIDER_ID,
      requireDisplayName: false
    }
  ]
});
// [END auth_fui_start_email_options_modular]