// This snippet file was generated by processing the source file:
// ./auth-next/firebaseui.js
//
// To make edits to the snippets in this file, please edit the source

// [START auth_fui_init_modular]
const ui = new firebaseui.auth.AuthUI(firebase.auth());
// [END auth_fui_init_modular]