// This snippet file was generated by processing the source file:
// ./firestore-react/test.firestore.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START add_alan_turing_react]
// Add a second document with a generated ID.
import { useTransition } from "react";
import { addDoc, collection } from "firebase/firestore"; 

function AddUserButton() {
  const [isPending, startTransition] = useTransition();

  function addUser() {
    startTransition(async () => {
      try {
        const docRef = await addDoc(collection(db, "users"), {
          first: "Alan",
          middle: "Mathison",
          last: "Turing",
          born: 1912
        });

        console.log("Document written with ID: ", docRef.id);
      } catch (e) {
        console.error("Error adding document: ", e);
      }
    });
  }

  return <button onClick={addUser} disabled={isPending}>Add user</button>;
}
// [END add_alan_turing_react]