// This snippet file was generated by processing the source file:
// ./firestore-react/test.firestore.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START cities_document_set_react]
import { useTransition } from "react";
import { doc, setDoc } from "firebase/firestore"; 

function AddCityButton({ data }) {
  const [isPending, startTransition] = useTransition();

  function addCity() {
    startTransition(async () => {
      await setDoc(doc(db, "cities", "new-city-id"), data);
    });
  }

  return <button onClick={addCity} disabled={isPending}>Add city</button>;
}
// [END cities_document_set_react]