// This snippet file was generated by processing the source file:
// ./firestore-react/test.firestore.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START count_aggregate_collection_react]
import { useEffect, useState } from "react";
import { collection, getCountFromServer } from "firebase/firestore"; 

function CityCount() {
  const [count, setCount] = useState(null);

  useEffect(() => {
    const coll = collection(db, "cities");
    getCountFromServer(coll).then((snapshot) => {
      console.log('count: ', snapshot.data().count);
      setCount(snapshot.data().count);
    });
  }, []);

  return <span>{count}</span>;
}
// [END count_aggregate_collection_react]