// This snippet file was generated by processing the source file:
// ./firestore-react/test.firestore.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START disable_network_react]
import { useTransition } from "react";
import { disableNetwork } from "firebase/firestore"; 

function DisableNetworkButton() {
  const [isPending, startTransition] = useTransition();

  function goOffline() {
    startTransition(async () => {
      await disableNetwork(db);
      console.log("Network disabled!");
      // Do offline actions
    });
  }

  return <button onClick={goOffline} disabled={isPending}>Go offline</button>;
}
// [END disable_network_react]