// This snippet file was generated by processing the source file:
// ./firestore-react/test.firestore.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START enable_network_react]
import { enableNetwork } from "firebase/firestore"; 

function EnableNetworkButton() {
  async function goOnline() {
    await enableNetwork(db);
    // Do online actions
  }

  return <button onClick={goOnline}>Go online</button>;
}
// [END enable_network_react]