// This snippet file was generated by processing the source file:
// ./firestore-react/test.firestore.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START enable_network_react]
import { useTransition } from "react";
import { enableNetwork } from "firebase/firestore"; 

function EnableNetworkButton() {
  const [isPending, startTransition] = useTransition();

  function goOnline() {
    startTransition(async () => {
      await enableNetwork(db);
      // Do online actions
    });
  }

  return <button onClick={goOnline} disabled={isPending}>Go online</button>;
}
// [END enable_network_react]