// This snippet file was generated by processing the source file:
// ./firestore-react/test.firestore.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START firestore_query_subcollection_react]
import { useEffect, useState } from "react";
import { collection, getDocs } from "firebase/firestore";

function LandmarkList() {
  const [landmarks, setLandmarks] = useState([]);

  useEffect(() => {
    // Query a reference to a subcollection
    getDocs(collection(db, "cities", "SF", "landmarks")).then((querySnapshot) => {
      const landmarks = [];
      querySnapshot.forEach((doc) => {
        // doc.data() is never undefined for query doc snapshots
        console.log(doc.id, " => ", doc.data());
        landmarks.push({ id: doc.id, ...doc.data() });
      });
      setLandmarks(landmarks);
    });
  }, []);

  return (
    <ul>
      {landmarks.map((landmark) => (
        <li key={landmark.id}>{landmark.name}</li>
      ))}
    </ul>
  );
}
// [END firestore_query_subcollection_react]