// This snippet file was generated by processing the source file:
// ./firestore-react/test.firestore.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START fs_collection_group_query_react]
import { useEffect, useState } from "react";
import { collectionGroup, query, where, getDocs } from "firebase/firestore";  

function MuseumList() {
  const [landmarks, setLandmarks] = useState([]);

  useEffect(() => {
    const museums = query(collectionGroup(db, 'landmarks'), where('type', '==', 'museum'));
    getDocs(museums).then((querySnapshot) => {
      const landmarks = [];
      querySnapshot.forEach((doc) => {
          console.log(doc.id, ' => ', doc.data());
          landmarks.push({ id: doc.id, ...doc.data() });
      });
      setLandmarks(landmarks);
    });
  }, []);

  return (
    <ul>
      {landmarks.map((landmark) => (
        <li key={landmark.id}>{landmark.name}</li>
      ))}
    </ul>
  );
}
// [END fs_collection_group_query_react]