// This snippet file was generated by processing the source file:
// ./firestore-react/test.firestore.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START get_document_react]
import { useEffect, useState } from "react";
import { doc, getDoc } from "firebase/firestore";

function CityDetails() {
  const [city, setCity] = useState(null);

  useEffect(() => {
    const docRef = doc(db, "cities", "SF");
    getDoc(docRef).then((docSnap) => {
      if (docSnap.exists()) {
        console.log("Document data:", docSnap.data());
        setCity(docSnap.data());
      } else {
        // docSnap.data() will be undefined in this case
        console.log("No such document!");
      }
    });
  }, []);

  return city ? <p>{city.name}</p> : <p>Loading...</p>;
}
// [END get_document_react]