// This snippet file was generated by processing the source file:
// ./firestore-react/test.firestore.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START get_all_users_react]
import { useEffect, useState } from "react";
import { collection, getDocs } from "firebase/firestore"; 

function UserList() {
  const [users, setUsers] = useState([]);

  useEffect(() => {
    getDocs(collection(db, "users")).then((querySnapshot) => {
      const users = [];
      querySnapshot.forEach((doc) => {
        console.log(doc.id, "=>", doc.data());
        users.push({ id: doc.id, ...doc.data() });
      });
      setUsers(users);
    });
  }, []);

  return (
    <ul>
      {users.map((user) => (
        <li key={user.id}>{user.first} {user.last}</li>
      ))}
    </ul>
  );
}
// [END get_all_users_react]