// This snippet file was generated by processing the source file:
// ./firestore-react/test.firestore.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START get_document_options_react]
import { useEffect, useState } from "react";
import { doc, getDocFromCache } from "firebase/firestore";

function CityDetails() {
  const [city, setCity] = useState(null);

  useEffect(() => {
    const docRef = doc(db, "cities", "SF");

    // Get a document, forcing the SDK to fetch from the offline cache.
    getDocFromCache(docRef).then((doc) => {
      // Document was found in the cache. If no cached document exists,
      // an error will be returned to the 'catch' block below.
      console.log("Cached document data:", doc.data());
      setCity(doc.data());
    }).catch((e) => {
      console.log("Error getting cached document:", e);
    });
  }, []);

  return city ? <p>{city.name}</p> : <p>Loading...</p>;
}
// [END get_document_options_react]