// This snippet file was generated by processing the source file:
// ./firestore-react/test.firestore.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START get_custom_object_react]
import { useEffect, useState } from "react";
import { doc, getDoc} from "firebase/firestore"; 

function CityDetails() {
  const [city, setCity] = useState(null);

  useEffect(() => {
    const ref = doc(db, "cities", "LA").withConverter(cityConverter);
    getDoc(ref).then((docSnap) => {
      if (docSnap.exists()) {
        // Convert to City object
        const city = docSnap.data();
        // Use a City instance method
        console.log(city.toString());
        console.log(city.name, city.state, city.country);
        setCity(city);
      } else {
        console.log("No such document!");
      }
    });
  }, []);

  return city ? <p>{city.toString()}</p> : <p>Loading...</p>;
}
// [END get_custom_object_react]