// This snippet file was generated by processing the source file:
// ./firestore-react/test.firestore.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START get_multiple_all_react]
import { useEffect, useState } from "react";
import { collection, getDocs } from "firebase/firestore";

function CityList() {
  const [cities, setCities] = useState([]);

  useEffect(() => {
    getDocs(collection(db, "cities")).then((querySnapshot) => {
      const cities = [];
      querySnapshot.forEach((doc) => {
        // doc.data() is never undefined for query doc snapshots
        console.log(doc.id, " => ", doc.data());
        cities.push({ id: doc.id, ...doc.data() });
      });
      setCities(cities);
    });
  }, []);

  return (
    <ul>
      {cities.map((city) => (
        <li key={city.id}>{city.name}</li>
      ))}
    </ul>
  );
}
// [END get_multiple_all_react]