// This snippet file was generated by processing the source file:
// ./firestore-react/test.firestore.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START handle_listen_errors_react]
import { useEffect } from "react";
import { collection, onSnapshot } from "firebase/firestore";

function CitiesListener() {
  useEffect(() => {
    return onSnapshot(
      collection(db, "cities"), 
      (snapshot) => {
        // ...
      },
      (error) => {
        // ...
      });
  }, []);

  return null;
}
// [END handle_listen_errors_react]