// This snippet file was generated by processing the source file:
// ./firestore-react/test.firestore.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START listen_multiple_react]
import { useEffect, useState, startTransition, ViewTransition } from "react";
import { collection, query, where, onSnapshot } from "firebase/firestore";

function CaliforniaCities() {
  const [cities, setCities] = useState([]);

  useEffect(() => {
    const q = query(collection(db, "cities"), where("state", "==", "CA"));
    // Realtime updates aren't urgent user input, so apply them in a
    // Transition. This keeps the page responsive and lets <ViewTransition>
    // animate cities as they're added and removed.
    return onSnapshot(q, (querySnapshot) => {
      const cities = [];
      querySnapshot.forEach((doc) => {
          cities.push({ id: doc.id, name: doc.data().name });
      });
      startTransition(() => setCities(cities));
    });
  }, []);

  return (
    <ul>
      {cities.map((city) => (
        <ViewTransition key={city.id}>
          <li>{city.name}</li>
        </ViewTransition>
      ))}
    </ul>
  );
}
// [END listen_multiple_react]