// This snippet file was generated by processing the source file:
// ./firestore-react/test.firestore.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START listen_for_users_react]
import { useEffect, useState } from "react";
import { collection, where, query, onSnapshot } from "firebase/firestore"; 

function UserList() {
  const [users, setUsers] = useState([]);

  useEffect(() => {
    const q = query(collection(db, "users"), where("born", "<", 1900));
    // onSnapshot returns an unsubscribe function. Returning it from the effect
    // detaches the listener when the component unmounts.
    return onSnapshot(q, (snapshot) => {
      console.log("Current users born before 1900:");
      const users = [];
      snapshot.forEach((userSnapshot) => {
        console.log(userSnapshot.data());
        users.push({ id: userSnapshot.id, ...userSnapshot.data() });
      });
      setUsers(users);
    });
  }, []);

  return (
    <ul>
      {users.map((user) => (
        <li key={user.id}>{user.first} {user.last}</li>
      ))}
    </ul>
  );
}
// [END listen_for_users_react]