// This snippet file was generated by processing the source file:
// ./firestore-react/test.firestore.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START listen_multiple_react]
import { useEffect, useState } from "react";
import { collection, query, where, onSnapshot } from "firebase/firestore";

function CityList({ state }) {
  const [cities, setCities] = useState([]);

  useEffect(() => {
    const q = query(collection(db, "cities"), where("state", "==", state));
    return onSnapshot(q, (querySnapshot) => {
      const cities = [];
      querySnapshot.forEach((doc) => {
          cities.push({ id: doc.id, name: doc.data().name });
      });
      setCities(cities);
    });
  }, [state]);

  return (
    <ul>
      {cities.map((city) => (
        <li key={city.id}>{city.name}</li>
      ))}
    </ul>
  );
}
// [END listen_multiple_react]