// This snippet file was generated by processing the source file:
// ./firestore-react/test.firestore.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START new_document_react]
import { collection, doc, setDoc } from "firebase/firestore"; 

function AddCityButton({ data }) {
  async function addCity() {
    // Add a new document with a generated id
    const newCityRef = doc(collection(db, "cities"));

    // later...
    await setDoc(newCityRef, data);
  }

  return <button onClick={addCity}>Add city</button>;
}
// [END new_document_react]