// This snippet file was generated by processing the source file:
// ./firestore-react/test.firestore.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START one_disjunction_react]
query(collectionRef, where("a", "==", 1));
// [END one_disjunction_react]