// This snippet file was generated by processing the source file:
// ./firestore-react/test.firestore.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START server_timestamp_resolution_options_react]
import { useEffect, useState } from "react";
import { doc, updateDoc, serverTimestamp, onSnapshot } from "firebase/firestore";

function ObjectTimestamp() {
  const [timestamp, setTimestamp] = useState(null);

  useEffect(() => {
    // Perform an update followed by an immediate read without
    // waiting for the update to complete. Due to the snapshot
    // options we will get two results: one with an estimate
    // timestamp and one with the resolved server timestamp.
    const docRef = doc(db, 'objects', 'some-id');
    updateDoc(docRef, {
        timestamp: serverTimestamp()
    });

    return onSnapshot(docRef, (snapshot) => {
      const data = snapshot.data({
        // Options: 'estimate', 'previous', or 'none'
        serverTimestamps: "estimate"
      });
      console.log(
          'Timestamp: ' + data.timestamp +
          ', pending: ' + snapshot.metadata.hasPendingWrites);
      setTimestamp(data.timestamp);
    });
  }, []);

  return <span>{timestamp ? timestamp.toDate().toString() : null}</span>;
}
// [END server_timestamp_resolution_options_react]