// This snippet file was generated by processing the source file:
// ./firestore-react/test.firestore.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START set_document_react]
import { useTransition } from "react";
import { doc, setDoc } from "firebase/firestore"; 

function AddCityButton() {
  const [isPending, startTransition] = useTransition();

  function addCity() {
    startTransition(async () => {
      // Add a new document in collection "cities"
      await setDoc(doc(db, "cities", "LA"), {
        name: "Los Angeles",
        state: "CA",
        country: "USA"
      });
    });
  }

  return <button onClick={addCity} disabled={isPending}>Add city</button>;
}
// [END set_document_react]