// This snippet file was generated by processing the source file:
// ./firestore-react/test.firestore.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START set_with_merge_react]
import { doc, setDoc } from "firebase/firestore"; 

function UpdateCityButton() {
  async function updateCity() {
    const cityRef = doc(db, 'cities', 'BJ');
    await setDoc(cityRef, { capital: true }, { merge: true });
  }

  return <button onClick={updateCity}>Update city</button>;
}
// [END set_with_merge_react]