// This snippet file was generated by processing the source file:
// ./firestore-react/test.firestore.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START set_document_react]
import { doc, setDoc } from "firebase/firestore"; 

function AddCityButton() {
  async function addCity() {
    // Add a new document in collection "cities"
    await setDoc(doc(db, "cities", "LA"), {
      name: "Los Angeles",
      state: "CA",
      country: "USA"
    });
  }

  return <button onClick={addCity}>Add city</button>;
}
// [END set_document_react]