// This snippet file was generated by processing the source file:
// ./firestore-react/test.firestore.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START simple_query_not_equal_react]
const notCapitalQuery = query(citiesRef, where("capital", "!=", false));
// [END simple_query_not_equal_react]