// This snippet file was generated by processing the source file:
// ./firestore-react/test.firestore.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START subcollection_reference_react]
import { doc } from "firebase/firestore"; 

const messageRef = doc(db, "rooms", "roomA", "messages", "message1");
// [END subcollection_reference_react]