// This snippet file was generated by processing the source file:
// ./firestore-react/test.firestore.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START transaction_promise_react]
import { useTransition } from "react";
import { doc, runTransaction } from "firebase/firestore";

function IncrementPopulationButton() {
  const [isPending, startTransition] = useTransition();

  function incrementPopulation() {
    startTransition(async () => {
      // Create a reference to the SF doc.
      const sfDocRef = doc(db, "cities", "SF");

      try {
        const newPopulation = await runTransaction(db, async (transaction) => {
          const sfDoc = await transaction.get(sfDocRef);
          if (!sfDoc.exists()) {
            throw "Document does not exist!";
          }

          const newPop = sfDoc.data().population + 1;
          if (newPop <= 1000000) {
            transaction.update(sfDocRef, { population: newPop });
            return newPop;
          } else {
            return Promise.reject("Sorry! Population is too big");
          }
        });

        console.log("Population increased to ", newPopulation);
      } catch (e) {
        // This will be a "population is too big" error.
        console.error(e);
      }
    });
  }

  return <button onClick={incrementPopulation} disabled={isPending}>Increment population</button>;
}
// [END transaction_promise_react]