// This snippet file was generated by processing the source file:
// ./firestore-react/test.firestore.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START transaction_react]
import { useTransition } from "react";
import { runTransaction } from "firebase/firestore";

function IncrementPopulationButton({ sfDocRef }) {
  const [isPending, startTransition] = useTransition();

  function incrementPopulation() {
    startTransition(async () => {
      try {
        await runTransaction(db, async (transaction) => {
          const sfDoc = await transaction.get(sfDocRef);
          if (!sfDoc.exists()) {
            throw "Document does not exist!";
          }

          const newPopulation = sfDoc.data().population + 1;
          transaction.update(sfDocRef, { population: newPopulation });
        });
        console.log("Transaction successfully committed!");
      } catch (e) {
        console.log("Transaction failed: ", e);
      }
    });
  }

  return <button onClick={incrementPopulation} disabled={isPending}>Increment population</button>;
}
// [END transaction_react]