// This snippet file was generated by processing the source file:
// ./firestore-react/test.firestore.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START update_delete_field_react]
import { doc, updateDoc, deleteField } from "firebase/firestore";

function RemoveCapitalButton() {
  async function removeCapital() {
    const cityRef = doc(db, 'cities', 'BJ');

    // Remove the 'capital' field from the document
    await updateDoc(cityRef, {
        capital: deleteField()
    });
  }

  return <button onClick={removeCapital}>Remove capital</button>;
}
// [END update_delete_field_react]