// This snippet file was generated by processing the source file:
// ./firestore-react/test.firestore.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START update_document_increment_react]
import { doc, updateDoc, increment } from "firebase/firestore";

function IncrementPopulationButton() {
  async function incrementPopulation() {
    const washingtonRef = doc(db, "cities", "DC");

    // Atomically increment the population of the city by 50.
    await updateDoc(washingtonRef, {
        population: increment(50)
    });
  }

  return <button onClick={incrementPopulation}>Increment population</button>;
}
// [END update_document_increment_react]