// This snippet file was generated by processing the source file:
// ./firestore-react/test.firestore.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START update_document_react]
import { doc, updateDoc } from "firebase/firestore";

function UpdateCityButton() {
  async function updateCity() {
    const washingtonRef = doc(db, "cities", "DC");

    // Set the "capital" field of the city 'DC'
    await updateDoc(washingtonRef, {
      capital: true
    });
  }

  return <button onClick={updateCity}>Update city</button>;
}
// [END update_document_react]