// This snippet file was generated by processing the source file:
// ./firestore-react/test.firestore.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START update_with_server_timestamp_react]
import { useTransition } from "react";
import { updateDoc, serverTimestamp } from "firebase/firestore";

function UpdateTimestampButton() {
  const [isPending, startTransition] = useTransition();

  function update() {
    startTransition(async () => {
      const docRef = doc(db, 'objects', 'some-id');

      // Update the timestamp field with the value from the server
      const updateTimestamp = await updateDoc(docRef, {
          timestamp: serverTimestamp()
      });
    });
  }

  return <button onClick={update} disabled={isPending}>Update</button>;
}
// [END update_with_server_timestamp_react]