// This snippet file was generated by processing the source file:
// ./firestore-react/test.firestore.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START update_document_array_react]
import { useTransition } from "react";
import { doc, updateDoc, arrayUnion, arrayRemove } from "firebase/firestore";

function UpdateRegionsButton() {
  const [isPending, startTransition] = useTransition();

  function updateRegions() {
    startTransition(async () => {
      const washingtonRef = doc(db, "cities", "DC");

      // Atomically add a new region to the "regions" array field.
      await updateDoc(washingtonRef, {
          regions: arrayUnion("greater_virginia")
      });

      // Atomically remove a region from the "regions" array field.
      await updateDoc(washingtonRef, {
          regions: arrayRemove("east_coast")
      });
    });
  }

  return <button onClick={updateRegions} disabled={isPending}>Update regions</button>;
}
// [END update_document_array_react]