// This snippet file was generated by processing the source file:
// ./firestore-react/test.firestore.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START update_document_increment_react]
import { useTransition } from "react";
import { doc, updateDoc, increment } from "firebase/firestore";

function IncrementPopulationButton() {
  const [isPending, startTransition] = useTransition();

  function incrementPopulation() {
    startTransition(async () => {
      const washingtonRef = doc(db, "cities", "DC");

      // Atomically increment the population of the city by 50.
      await updateDoc(washingtonRef, {
          population: increment(50)
      });
    });
  }

  return <button onClick={incrementPopulation} disabled={isPending}>Increment population</button>;
}
// [END update_document_increment_react]