// This snippet file was generated by processing the source file:
// ./firestore-react/test.firestore.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START valid_filter_and_order_react]
import { query, where, orderBy } from "firebase/firestore";  

const q = query(citiesRef, where("population", ">", 100000), orderBy("population"));
// [END valid_filter_and_order_react]