// This snippet file was generated by processing the source file:
// ./firestore-react/test.firestore.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START write_batch_react]
import { useTransition } from "react";
import { writeBatch, doc } from "firebase/firestore"; 

function CommitBatchButton() {
  const [isPending, startTransition] = useTransition();

  function commitBatch() {
    startTransition(async () => {
      // Get a new write batch
      const batch = writeBatch(db);

      // Set the value of 'NYC'
      const nycRef = doc(db, "cities", "NYC");
      batch.set(nycRef, {name: "New York City"});

      // Update the population of 'SF'
      const sfRef = doc(db, "cities", "SF");
      batch.update(sfRef, {"population": 1000000});

      // Delete the city 'LA'
      const laRef = doc(db, "cities", "LA");
      batch.delete(laRef);

      // Commit the batch
      await batch.commit();
    });
  }

  return <button onClick={commitBatch} disabled={isPending}>Commit batch</button>;
}
// [END write_batch_react]