// This snippet file was generated by processing the source file:
// ./firestore-react/test.firestore.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START write_batch_react]
import { writeBatch, doc } from "firebase/firestore"; 

function CommitBatchButton() {
  async function commitBatch() {
    // Get a new write batch
    const batch = writeBatch(db);

    // Set the value of 'NYC'
    const nycRef = doc(db, "cities", "NYC");
    batch.set(nycRef, {name: "New York City"});

    // Update the population of 'SF'
    const sfRef = doc(db, "cities", "SF");
    batch.update(sfRef, {"population": 1000000});

    // Delete the city 'LA'
    const laRef = doc(db, "cities", "LA");
    batch.delete(laRef);

    // Commit the batch
    await batch.commit();
  }

  return <button onClick={commitBatch}>Commit batch</button>;
}
// [END write_batch_react]