// This snippet file was generated by processing the source file:
// ./storage-react/download-files.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START storage_download_via_url_react]
import { useEffect, useState } from "react";
import { getStorage, ref, getDownloadURL } from "firebase/storage";

function StarsImage() {
  const [url, setUrl] = useState(null);

  useEffect(() => {
    const storage = getStorage();
    const starsRef = ref(storage, 'images/stars.jpg');

    getDownloadURL(starsRef)
      .then((url) => {
        // `url` is the download URL for 'images/stars.jpg'

        // This can be downloaded directly:
        const xhr = new XMLHttpRequest();
        xhr.responseType = 'blob';
        xhr.onload = (event) => {
          const blob = xhr.response;
        };
        xhr.open('GET', url);
        xhr.send();

        // Or inserted into an <img> element
        setUrl(url);
      })
      .catch((error) => {
        // Handle any errors
      });
  }, []);

  return <img src={url} />;
}
// [END storage_download_via_url_react]