// This snippet file was generated by processing the source file:
// ./firestore-temp/test.firestore.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START add_fields_syntax_modular]
const results = await db.pipeline()
  .collection("users")
  .addFields(field("firstName").stringConcat(" ", field("lastName")).as("fullName"))
  .execute();
// [END add_fields_syntax_modular]