// This snippet file was generated by processing the source file:
// ./firestore-temp/test.firestore.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START aggregate_data_modular]
await db.collection("cities").doc("SF").set({name: "San Francisco", state: "CA", country: "USA", population: 870000});
await db.collection("cities").doc("LA").set({name: "Los Angeles", state: "CA", country: "USA", population: 3970000});
await db.collection("cities").doc("NY").set({name: "New York", state: "NY", country: "USA", population: 8530000});
await db.collection("cities").doc("TOR").set({name: "Toronto", state: null, country: "Canada", population: 2930000});
await db.collection("cities").doc("MEX").set({name: "Mexico City", state: null, country: "Mexico", population: 9200000});
// [END aggregate_data_modular]