// This snippet file was generated by processing the source file:
// ./firestore-temp/test.firestore.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START aggregate_syntax_modular]
const cities = await db.pipeline()
  .collection("cities")
  .aggregate(
      countAll().as("total"),
      average("population").as("averagePopulation")
  ).execute();
// [END aggregate_syntax_modular]