// This snippet file was generated by processing the source file:
// ./firestore-temp/test.firestore.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START cond_function_modular]
const result = await db.pipeline()
  .collection("books")
  .select(
    field("tags").arrayConcat([
      conditional(
        field("pages").greaterThan(100),
        constant("longRead"),
        constant("shortRead")
      )
    ]).as("extendedTags")
  )
  .execute();
// [END cond_function_modular]