// This snippet file was generated by processing the source file:
// ./firestore-temp/test.firestore.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START count_distinct_modular]
const result = await db.pipeline()
  .collection("books")
  .aggregate(field("author").countDistinct().as("unique_authors"))
  .execute();
// [END count_distinct_modular]