// This snippet file was generated by processing the source file:
// ./firestore-temp/test.firestore.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START database_input_modular]
const results = await db.pipeline()
  .database()
  .sort(field("population").ascending())
  .execute();
// [END database_input_modular]