// This snippet file was generated by processing the source file:
// ./firestore-temp/test.firestore.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START define_stage_data_modular]
await db.collection("Authors").doc("author_123").set({
  id: "author_123",
  name: "Jane Austen"
});
// [END define_stage_data_modular]