// This snippet file was generated by processing the source file:
// ./firestore-temp/test.firestore.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START delete_dml_data_modular]
await db.collection("Users").doc("userID").set({
  id: "userID",
  address: {
    country: "USA",
    state: "CA"
  },
  __create_time__: Timestamp.fromMillis(946684800000)
});
// [END delete_dml_data_modular]