// This snippet file was generated by processing the source file:
// ./firestore-temp/test.firestore.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START document_input_modular]
const results = await db.pipeline()
  .documents([
    db.collection("cities").doc("SF"),
    db.collection("cities").doc("NYC")])
  .sort(field("name").ascending())
  .execute();
// [END document_input_modular]