// This snippet file was generated by processing the source file:
// ./firestore-temp/test.firestore.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START find_nearest_distance_modular]
const results = await db.pipeline()
.collection("cities")
.findNearest({
    field: "embedding",
    vectorValue: [1.3, 2.345],
    distanceMeasure: "euclidean",
    distanceField: "computedDistance",
})
.execute();
// [END find_nearest_distance_modular]