// This snippet file was generated by processing the source file:
// ./firestore-temp/test.firestore.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START find_nearest_distance_data_modular]
await db.collection("cities").doc("SF").set({name: "San Francisco", embedding: [1.0, -1.0]});
await db.collection("cities").doc("TO").set({name: "Toronto", embedding: [5.0, -10.0]});
await db.collection("cities").doc("AT").set({name: "Atlantis", embedding: [2.0, -4.0]});
// [END find_nearest_distance_data_modular]