// This snippet file was generated by processing the source file:
// ./firestore-temp/test.firestore.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START initial_data_modular]
await db.collection("cities").doc("SF").set({
  "name": "San Francisco",
  "population": 800000,
  "location": {
    "country": "USA",
    "state": "California"
  }
});
await db.collection("cities").doc("TO").set({
  "name": "Toronto",
  "population": 3000000,
  "province": "ON",
  "location": {
    "country": "Canada",
    "province": "Ontario"
  }
});
await db.collection("cities").doc("NY").set({
  "name": "New York",
  "location": {
    "country": "USA",
    "state": "New York"
  }
});
await db.collection("cities").doc("AT").set({
  "name": "Atlantis",
});
// [END initial_data_modular]