// This snippet file was generated by processing the source file:
// ./firestore-temp/test.firestore.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START input_stages_modular]
let results;

// Return all restaurants in San Francisco
results = await db.pipeline().collection("cities/sf/restaurants").execute();

// Return all restaurants
results = await db.pipeline().collectionGroup("restaurants").execute();

// Return all documents across all collections in the database (the entire database)
results = await db.pipeline().database().execute();

// Batch read of 3 documents
results = await db.pipeline().documents([
  db.collection("cities").doc("SF"),
  db.collection("cities").doc("DC"),
  db.collection("cities").doc("NY"),
]).execute();
// [END input_stages_modular]