// This snippet file was generated by processing the source file:
// ./firestore-temp/test.firestore.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START min_logical_function_modular]
const result = await db.pipeline()
  .collection("books")
  .select(
    field("rating").logicalMinimum(5).as("cappedRating")
  )
  .execute();
// [END min_logical_function_modular]