// This snippet file was generated by processing the source file:
// ./firestore-temp/test.firestore.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START query_explain_modular]
const q = db.collection("cities").where("country", "==", "USA");
const options = { analyze: false };

const explainResults = await q.explain(options);

const metrics = explainResults.metrics;
const plan = metrics.planSummary;
// [END query_explain_modular]