// This snippet file was generated by processing the source file:
// ./firestore-temp/test.firestore.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START remove_fields_nested_data_modular]
await db.collection("cities").doc("SF").set({
  name: "San Francisco", location: {country: "USA", state: "California"}
});
await db.collection("cities").doc("TO").set({
  name: "Toronto", location: {country: "Canada", province: "Ontario"}
});
// [END remove_fields_nested_data_modular]