// This snippet file was generated by processing the source file:
// ./firestore-temp/test.firestore.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START sample_syntax_modular]
let sampled = await db.pipeline()
  .database()
  .sample(50)
  .execute();

sampled = await db.pipeline()
  .database()
  .sample({ percentage: 0.5 })
  .execute();
// [END sample_syntax_modular]