// This snippet file was generated by processing the source file:
// ./firestore-temp/test.firestore.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START sample_documents_modular]
const sampled = await db.pipeline()
  .collection("cities")
  .sample(1)
  .execute();
// [END sample_documents_modular]