// This snippet file was generated by processing the source file:
// ./firestore-temp/test.firestore.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START search_score_data_modular]
await db.collection("Restaurants").add({
  name: "The Waffle Hub",
  description: "Everything waffles!"
});
// [END search_score_data_modular]