// This snippet file was generated by processing the source file:
// ./firestore-temp/test.firestore.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START select_position_data_modular]
await db.collection("cities").doc("SF").set({
  name: "San Francisco", population: 800000, location: {country: "USA", state: "California"}
});
await db.collection("cities").doc("TO").set({
  name: "Toronto", population: 3000000, location: {country: "Canada", province: "Ontario"}
});
// [END select_position_data_modular]