// This snippet file was generated by processing the source file:
// ./firestore-temp/test.firestore.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START sort_syntax_modular]
const results = await db.pipeline()
  .collection("cities")
  .sort(field("population").ascending())
  .execute();
// [END sort_syntax_modular]