// This snippet file was generated by processing the source file:
// ./firestore-temp/test.firestore.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START sort_comparison_modular]
const q = db.collection("cities")
  .orderBy("state")
  .orderBy("population", "desc");

const pipeline = db.pipeline()
  .collection("books")
  .sort(
    field("release_date").descending(), field("author").ascending()
  );
// [END sort_comparison_modular]