// This snippet file was generated by processing the source file:
// ./firestore-temp/test.firestore.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START subcollection_input_modular]
const results = await db.pipeline()
  .collection("cities/NY/departments")
  .sort(field("employees").ascending())
  .execute();
// [END subcollection_input_modular]