// This snippet file was generated by processing the source file:
// ./firestore-temp/test.firestore.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START to_array_expression_stage_data_modular]
await db.collection("Projects").doc("project_1").set({
  id: "project_1",
  name: "Alpha Build"
});
await db.collection("Tasks").add({
  project_id: "project_1",
  title: "System Architecture"
});
await db.collection("Tasks").add({
  project_id: "project_1",
  title: "Database Schema Design"
});
// [END to_array_expression_stage_data_modular]