// This snippet file was generated by processing the source file:
// ./firestore-temp/test.firestore.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START where_multiple_stages_modular]
const cities = await db.pipeline()
  .collection("cities")
  .where(field("location.country").equal("USA"))
  .where(field("population").greaterThan(500000))
  .execute();
// [END where_multiple_stages_modular]