// This snippet file was generated by processing the source file:
// ./firestore-temp/test.firestore.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START where_stage_order_modular]
const cities = await db.pipeline()
  .collection("cities")
  .limit(10)
  .where(field("location.country").equal("USA"))
  .execute();
// [END where_stage_order_modular]