// This snippet file was generated by processing the source file:
// ./auth/saml.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START auth_saml_signin_redirect_modular]
firebase.auth().signInWithRedirect(provider);
// [END auth_saml_signin_redirect_modular]