// This snippet file was generated by processing the source file:
// ./auth-next/github.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START auth_github_provider_params_modular]
provider.setCustomParameters({
  'allow_signup': 'false'
});
// [END auth_github_provider_params_modular]