// This snippet file was generated by processing the source file:
// ./auth-next/github.js
//
// To make edits to the snippets in this file, please edit the source

// [START auth_github_provider_create_modular]
import { GithubAuthProvider } from "firebase/auth";

const provider = new GithubAuthProvider();
// [END auth_github_provider_create_modular]