// This snippet file was generated by processing the source file:
// ./auth-next/github.js
//
// To make edits to the snippets in this file, please edit the source

// [START auth_github_provider_credential_modular]
import { GithubAuthProvider } from "firebase/auth";

const credential = GithubAuthProvider.credential(token);
// [END auth_github_provider_credential_modular]