// This snippet file was generated by processing the source file:
// ./auth-react/service-worker-sessions.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START auth_svc_listen_activate_react]
self.addEventListener('activate', (event) => {
  event.waitUntil(clients.claim());
});
// [END auth_svc_listen_activate_react]