// This snippet file was generated by processing the source file:
// ./database-react/index.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START rtdb_get_reference_react]
import { getDatabase } from "firebase/database";

const database = getDatabase();
// [END rtdb_get_reference_react]