// This snippet file was generated by processing the source file:
// ./auth-next/manage.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START auth_update_user_profile_modular]
import { getAuth, updateProfile } from "firebase/auth";
const auth = getAuth();
updateProfile(auth.currentUser, {
  displayName: "Jane Q. User", photoURL: "https://example.com/jane-q-user/profile.jpg"
}).then(() => {
  // Profile updated!
  // ...
}).catch((error) => {
  // An error occurred
  // ...
});
// [END auth_update_user_profile_modular]