// This snippet file was generated by processing the source file:
// ./auth-next/manage.js
//
// To make edits to the snippets in this file, please edit the source

// [START auth_reauth_with_credential_modular]
import { getAuth, reauthenticateWithCredential } from "firebase/auth";

const auth = getAuth();
const user = auth.currentUser;

// TODO(you): prompt the user to re-provide their sign-in credentials
const credential = promptForCredentials();

reauthenticateWithCredential(user, credential).then(() => {
  // User re-authenticated.
}).catch((error) => {
  // An error ocurred
  // ...
});
// [END auth_reauth_with_credential_modular]