// This snippet file was generated by processing the source file:
// ./auth-next/manage.js
//
// To make edits to the snippets in this file, please edit the source

// [START auth_send_password_reset_modular]
import { getAuth, sendPasswordResetEmail } from "firebase/auth";

const auth = getAuth();
const emailAddress = "user@example.com";

sendPasswordResetEmail(auth, emailAddress).then(() => {
  // Email sent.
}).catch((error) => {
  // An error ocurred
  // ...
});
// [END auth_send_password_reset_modular]