// This snippet file was generated by processing the source file:
// ./storage-next/index.js
//
// To make edits to the snippets in this file, please edit the source

// [START storage_custom_app_modular]
import { getStorage } from "firebase/storage";

// Get the default bucket from a custom firebase.app.App
const storage1 = getStorage(customApp);

// Get a non-default bucket from a custom firebase.app.App
const storage2 = getStorage(customApp, "gs://my-custom-bucket");
// [END storage_custom_app_modular]