// This snippet file was generated by processing the source file:
// ./auth-react/phone-auth.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START auth_phone_signin_react]
import { useRef, useState, useActionState } from "react";
import { getAuth, signInWithPhoneNumber } from "firebase/auth";

function PhoneSignInForm() {
  // Created by the setupRecaptcha ref callback shown above.
  const recaptchaVerifier = useRef(null);
  const [confirmationResult, setConfirmationResult] = useState(null);

  const [error, signIn, isPending] = useActionState(async (previousError, formData) => {
    const phoneNumber = formData.get("phoneNumber");
    const appVerifier = recaptchaVerifier.current;

    const auth = getAuth();
    try {
      const confirmationResult = await signInWithPhoneNumber(auth, phoneNumber, appVerifier);
      // SMS sent. Prompt user to type the code from the message, then sign the
      // user in with confirmationResult.confirm(code).
      setConfirmationResult(confirmationResult);
      // ...
      return null;
    } catch (error) {
      // Error; SMS not sent
      // ...
      return error.message;
    }
  }, null);

  return confirmationResult ? (
    <VerifyCodeForm confirmationResult={confirmationResult} />
  ) : (
    <form action={signIn}>
      <input name="phoneNumber" type="tel" />
      <button ref={setupRecaptcha} type="submit" disabled={isPending}>Sign in</button>
      {error ? <p>{error}</p> : null}
    </form>
  );
}
// [END auth_phone_signin_react]