// This snippet file was generated by processing the source file:
// ./auth-react/phone-auth.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START auth_get_recaptcha_response_react]
const recaptchaResponse = grecaptcha.getResponse(recaptchaWidgetId.current);
// [END auth_get_recaptcha_response_react]