// This snippet file was generated by processing the source file:
// ./auth-react/phone-auth.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START auth_phone_recaptcha_verifier_invisible_react]
import { useRef } from "react";
import { getAuth, RecaptchaVerifier } from "firebase/auth";

function PhoneSignInForm() {
  const recaptchaVerifier = useRef(null);

  // React calls this with the element on mount and with the cleanup on unmount.
  function setupRecaptcha(container) {
    const auth = getAuth();
    recaptchaVerifier.current = new RecaptchaVerifier(auth, container, {
      'size': 'invisible',
      'callback': (response) => {
        // reCAPTCHA solved, allow signInWithPhoneNumber.
        onSignInSubmit();
      }
    });
    return () => {
      recaptchaVerifier.current.clear();
      recaptchaVerifier.current = null;
    };
  }

  return <button ref={setupRecaptcha} type="submit">Sign in</button>;
}
// [END auth_phone_recaptcha_verifier_invisible_react]