// This snippet file was generated by processing the source file:
// snippets/firestore-next/test-solution-arrays/post_with_map.js
//
// To make edits to the snippets in this file, please edit the source

// [START modular_post_with_map]
// Sample document in the 'posts' collection
{
    title: "My great post",
    categories: {
        "technology": true,
        "opinion": true,
        "cats": true
    }
}
// [END modular_post_with_map]