// This snippet file was generated by processing the source file:
// ./firestore-next/test.solution-arrays.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START query_in_category_timestamp_invalid_modular]
import { collection, query, where, orderBy, Firestore } from "firebase/firestore";

const q = query(collection(db, "posts"),
    where("categories.cats", "==", true),
    orderBy("timestamp"));
// [END query_in_category_timestamp_invalid_modular]