// This snippet file was generated by processing the source file:
// ./auth-next/index.js
//
// To make edits to the snippets in this file, please edit the source

// [START auth_set_language_code_modular]
import { getAuth } from "firebase/auth";

const auth = getAuth(firebaseApp);
auth.languageCode = 'it';
// To apply the default browser preference instead of explicitly setting it.
// firebase.auth().useDeviceLanguage();
// [END auth_set_language_code_modular]