// This snippet file was generated by processing the source file:
// ./messaging-react/index.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START messaging_register_react]
import { useEffect, useState } from "react";
import { getMessaging, onRegistered, register } from "firebase/messaging";

function InstallationId() {
  const [installationId, setInstallationId] = useState(null);

  useEffect(() => {
    const messaging = getMessaging();

    // 1. Implement callback to receive the Firebase installation ID upon registration.
    // This is triggered every time a manual register() finishes, a FID change
    // is detected, or a pushsubscriptionchange event is fired.
    const unsubscribe = onRegistered(messaging, (installationId) => {
      console.log('Registered installation ID:', installationId);

      // Send the Firebase Installation ID to your app server and update the UI if needed.
      sendRegistrationToServer(installationId);
      setInstallationId(installationId);
    });

    // 2. You can also manually trigger registration (recommended on app startup)
    register(messaging, {
      vapidKey: '<YOUR_PUBLIC_VAPID_KEY_HERE>'
    }).then(() => {
      // Success! The Firebase Installation ID can be used to target messages to this app
      // instance and will be delivered asynchronously to your onRegistered() callback.
    }).catch((err) => {
      console.error('An error occurred while registering', err);
    });

    // onRegistered returns an unsubscribe function. Returning it from the effect
    // detaches the listener when the component unmounts.
    return unsubscribe;
  }, []);

  return <span>{installationId}</span>;
}
// [END messaging_register_react]