// This snippet file was generated by processing the source file:
// ./messaging-react/index.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START messaging_get_messaging_object_react]
import { getMessaging } from "firebase/messaging";

const messaging = getMessaging();
// [END messaging_get_messaging_object_react]