// This snippet file was generated by processing the source file:
// ./messaging-react/index.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START messaging_delete_token_react]
import { getMessaging, deleteToken } from "firebase/messaging";

function DeleteTokenButton() {
  async function deleteRegistrationToken() {
    const messaging = getMessaging();
    try {
      await deleteToken(messaging);
      console.log('Token deleted.');
      // ...
    } catch (err) {
      console.log('Unable to delete token. ', err);
    }
  }

  return <button onClick={deleteRegistrationToken}>Delete token</button>;
}
// [END messaging_delete_token_react]