// This snippet file was generated by processing the source file:
// ./messaging-react/index.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START messaging_get_token_react]
import { useEffect, useState } from "react";
import { getMessaging, getToken } from "firebase/messaging";

function RegistrationToken() {
  const [currentToken, setCurrentToken] = useState(null);

  useEffect(() => {
    // Get registration token. Initially this makes a network call, once retrieved
    // subsequent calls to getToken will return from cache.
    const messaging = getMessaging();
    getToken(messaging, { vapidKey: '<YOUR_PUBLIC_VAPID_KEY_HERE>' }).then((currentToken) => {
      if (currentToken) {
        // Send the token to your server and update the UI if necessary
        // ...
        setCurrentToken(currentToken);
      } else {
        // Show permission request UI
        console.log('No registration token available. Request permission to generate one.');
        // ...
      }
    }).catch((err) => {
      console.log('An error occurred while retrieving token. ', err);
      // ...
    });
  }, []);

  return <span>{currentToken}</span>;
}
// [END messaging_get_token_react]