// This snippet file was generated by processing the source file:
// ./messaging-react/index.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START messaging_receive_message_react]
// Handle incoming messages. Called when:
// - a message is received while the app has focus
// - the user clicks on an app notification created by a service worker
//   `messaging.onBackgroundMessage` handler.
import { useEffect, useState } from "react";
import { getMessaging, onMessage } from "firebase/messaging";

function LastMessage() {
  const [payload, setPayload] = useState(null);

  useEffect(() => {
    const messaging = getMessaging();
    // onMessage returns an unsubscribe function. Returning it from the effect
    // detaches the listener when the component unmounts.
    return onMessage(messaging, (payload) => {
      console.log('Message received. ', payload);
      // ...
      setPayload(payload);
    });
  }, []);

  return payload ? <pre>{JSON.stringify(payload)}</pre> : null;
}
// [END messaging_receive_message_react]