// This snippet file was generated by processing the source file:
// ./firestore-next/test.solution-aggregation.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START get_collection_ratings_modular]
import { collection, getDocs } from "firebase/firestore";

const ratingsRef = collection(db, "restaurants", "arinell-pizza", "ratings");
const ratingsDocs = await getDocs(ratingsRef);
// [END get_collection_ratings_modular]