// This snippet file was generated by processing the source file:
// ./firestore-next/test.solution-aggregation.js
//
// To make edits to the snippets in this file, please edit the source

// [START sample_doc_modular]
const arinellDoc = {
  name: 'Arinell Pizza',
  avgRating: 4.65,
  numRatings: 683
};
// [END sample_doc_modular]