// This snippet file was generated by processing the source file:
// ./firestore-next/test.solution-aggregation.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START sample_doc_modular]
const arinellDoc = {
  name: 'Arinell Pizza',
  avgRating: 4.65,
  numRatings: 683
};
// [END sample_doc_modular]