// This snippet file was generated by processing the source file:
// ./auth-react/link-multiple-accounts.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START auth_simple_link_react]
import { getAuth, linkWithCredential } from "firebase/auth";

function LinkAccountButton({ credential }) {
  async function link() {
    const auth = getAuth();
    try {
      const usercred = await linkWithCredential(auth.currentUser, credential);
      const user = usercred.user;
      console.log("Account linking success", user);
    } catch (error) {
      console.log("Account linking error", error);
    }
  }

  return <button onClick={link}>Link account</button>;
}
// [END auth_simple_link_react]