// This snippet file was generated by processing the source file:
// ./auth-react/link-multiple-accounts.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START auth_unlink_provider_react]
import { getAuth, unlink } from "firebase/auth";

function UnlinkButton({ providerId }) {
  async function unlinkProvider() {
    const auth = getAuth();
    try {
      await unlink(auth.currentUser, providerId);
      // Auth provider unlinked from account
      // ...
    } catch (error) {
      // An error happened
      // ...
    }
  }

  return <button onClick={unlinkProvider}>Unlink</button>;
}
// [END auth_unlink_provider_react]