// This snippet file was generated by processing the source file:
// ./auth-react/link-multiple-accounts.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START auth_anonymous_link_react]
import { getAuth, linkWithCredential } from "firebase/auth";

function UpgradeAccountButton({ credential }) {
  async function upgrade() {
    const auth = getAuth();
    try {
      const usercred = await linkWithCredential(auth.currentUser, credential);
      const user = usercred.user;
      console.log("Anonymous account successfully upgraded", user);
    } catch (error) {
      console.log("Error upgrading anonymous account", error);
    }
  }

  return <button onClick={upgrade}>Upgrade account</button>;
}
// [END auth_anonymous_link_react]