// This snippet file was generated by processing the source file:
// ./auth-react/link-multiple-accounts.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START auth_link_with_redirect_react]
import { getAuth, linkWithRedirect, GoogleAuthProvider } from "firebase/auth";
const provider = new GoogleAuthProvider();

function LinkGoogleButton() {
  async function link() {
    const auth = getAuth();
    await linkWithRedirect(auth.currentUser, provider)
      .then(/* ... */)
      .catch(/* ... */);
  }

  return <button onClick={link}>Link Google</button>;
}
// [END auth_link_with_redirect_react]