// This snippet file was generated by processing the source file:
// ./messaging-next/index.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START messaging_get_messaging_object_modular]
import { getMessaging } from "firebase/messaging";

const messaging = getMessaging();
// [END messaging_get_messaging_object_modular]