// This snippet file was generated by processing the source file:
// ./messaging-next/index.js
//
// To make edits to the snippets in this file, please edit the source

// [START messaging_get_messaging_object_modular]
import { getMessaging } from "firebase/messaging";

const messaging = getMessaging();
// [END messaging_get_messaging_object_modular]