// This snippet file was generated by processing the source file:
// ./auth-react/custom-dependencies.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START auth_only_browser_local_react]
import {initializeAuth, browserLocalPersistence} from "firebase/auth";
import {initializeApp} from "firebase/app";

// Initialize Firebase once at module scope (e.g. src/firebase.js), not inside a component.
const app = initializeApp({/** Your app config */});
const auth = initializeAuth(app, {
  persistence: browserLocalPersistence,
  // No popupRedirectResolver defined
});
// [END auth_only_browser_local_react]