// This snippet file was generated by processing the source file:
// ./auth-react/custom-dependencies.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START auth_get_auth_equivalent_react]
import {initializeAuth, browserLocalPersistence, browserPopupRedirectResolver, browserSessionPersistence, indexedDBLocalPersistence} from "firebase/auth";
import {initializeApp} from "firebase/app";

// Initialize Firebase once at module scope (e.g. src/firebase.js), not inside a component.
const app = initializeApp({/** Your app config */});
const auth = initializeAuth(app, {
  persistence: [indexedDBLocalPersistence, browserLocalPersistence, browserSessionPersistence],
  popupRedirectResolver: browserPopupRedirectResolver,
});
// [END auth_get_auth_equivalent_react]