// This snippet file was generated by processing the source file:
// ./auth-react/twitter.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START auth_twitter_provider_create_react]
import { TwitterAuthProvider } from "firebase/auth";

const provider = new TwitterAuthProvider();
// [END auth_twitter_provider_create_react]