// This snippet file was generated by processing the source file:
// ./auth-next/twitter.js
//
// To make edits to the snippets in this file, please edit the source

// [START auth_twitter_provider_create_modular]
import { TwitterAuthProvider } from "firebase/auth";

const provider = new TwitterAuthProvider();
// [END auth_twitter_provider_create_modular]