// This snippet file was generated by processing the source file:
// ./database-react/read-and-write.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START rtdb_social_star_transaction_react]
import { getDatabase, ref, runTransaction } from "firebase/database";

function StarButton({ uid, starred }) {
  async function toggleStar() {
    const db = getDatabase();
    const postRef = ref(db, '/posts/foo-bar-123');

    await runTransaction(postRef, (post) => {
      if (post) {
        if (post.stars && post.stars[uid]) {
          post.starCount--;
          post.stars[uid] = null;
        } else {
          post.starCount++;
          if (!post.stars) {
            post.stars = {};
          }
          post.stars[uid] = true;
        }
      }
      return post;
    });
  }

  return (
    <button onClick={toggleStar}>
      {starred ? 'Unstar' : 'Star'}
    </button>
  );
}
// [END rtdb_social_star_transaction_react]