// This snippet file was generated by processing the source file:
// ./database-react/read-and-write.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START rtdb_write_new_user_react]
import { getDatabase, ref, set } from "firebase/database";

function NewUserForm({ userId }) {
  async function writeUserData(formData) {
    const db = getDatabase();
    await set(ref(db, 'users/' + userId), {
      username: formData.get("name"),
      email: formData.get("email"),
      profile_picture : formData.get("imageUrl")
    });
  }

  return (
    <form action={writeUserData}>
      <input name="name" />
      <input name="email" type="email" />
      <input name="imageUrl" type="url" />
      <button type="submit">Save</button>
    </form>
  );
}
// [END rtdb_write_new_user_react]