// This snippet file was generated by processing the source file:
// ./database-react/read-and-write.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START rtdb_social_star_transaction_react]
import { useOptimistic, startTransition } from "react";
import { getDatabase, ref, runTransaction } from "firebase/database";

function StarButton({ uid, starred }) {
  const [optimisticStarred, setOptimisticStarred] = useOptimistic(starred);

  function toggleStar() {
    startTransition(async () => {
      // Show the new state right away. When the transaction settles, React
      // returns to the `starred` prop, which your listener has updated by then.
      setOptimisticStarred(!optimisticStarred);

      const db = getDatabase();
      const postRef = ref(db, '/posts/foo-bar-123');

      await runTransaction(postRef, (post) => {
        if (post) {
          if (post.stars && post.stars[uid]) {
            post.starCount--;
            post.stars[uid] = null;
          } else {
            post.starCount++;
            if (!post.stars) {
              post.stars = {};
            }
            post.stars[uid] = true;
          }
        }
        return post;
      });
    });
  }

  return (
    <button onClick={toggleStar}>
      {optimisticStarred ? 'Unstar' : 'Star'}
    </button>
  );
}
// [END rtdb_social_star_transaction_react]