// This snippet file was generated by processing the source file:
// ./database-react/read-and-write.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START rtdb_social_star_increment_react]
import { getDatabase, increment, ref, update } from "firebase/database";

function AddStarButton({ uid, postKey }) {
  async function addStar() {
    const dbRef = ref(getDatabase());

    const updates = {};
    updates[`posts/${postKey}/stars/${uid}`] = true;
    updates[`posts/${postKey}/starCount`] = increment(1);
    updates[`user-posts/${postKey}/stars/${uid}`] = true;
    updates[`user-posts/${postKey}/starCount`] = increment(1);
    await update(dbRef, updates);
  }

  return <button onClick={addStar}>Star</button>;
}
// [END rtdb_social_star_increment_react]