// This snippet file was generated by processing the source file:
// ./remoteconfig-next/index.js
//
// To make edits to the snippets in this file, please edit the source

// [START rc_fetch_config_callback_modular]
import { fetchAndActivate } from "firebase/remote-config";

fetchAndActivate(remoteConfig)
  .then(() => {
    // ...
  })
  .catch((err) => {
    // ...
  });
// [END rc_fetch_config_callback_modular]