// This snippet file was generated by processing the source file:
// ./remoteconfig-next/index.js
//
// To make edits to the snippets in this file, please edit the source

// [START rc_get_values_modular]
import { getValue } from "firebase/remote-config";

const val = getValue(remoteConfig, "welcome_messsage");
// [END rc_get_values_modular]