// This snippet file was generated by processing the source file:
// ./remoteconfig-next/index.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START rc_set_minimum_fetch_time_modular]
remoteConfig.settings.minimumFetchIntervalMillis = 3600000;
// [END rc_set_minimum_fetch_time_modular]