// This snippet file was generated by processing the source file:
// ./remoteconfig-next/index.js
//
// To make edits to the snippets in this file, please edit the source

// [START rc_set_minimum_fetch_time_modular]
remoteConfig.settings.minimumFetchIntervalMillis = 3600000;
// [END rc_set_minimum_fetch_time_modular]