// This snippet file was generated by processing the source file:
// ./remoteconfig-next/index.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START rc_set_default_values_modular]
remoteConfig.defaultConfig = {
  "welcome_message": "Welcome"
};
// [END rc_set_default_values_modular]