// This snippet file was generated by processing the source file:
// ./firestore-react/test.solution-arrays.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START post_with_map_advanced_react]
// The value of each entry in 'categories' is a unix timestamp
{
  title: "My great post",
  categories: {
    technology: 1502144665,
    opinion: 1502144665,
    cats: 1502144665
  }
}
// [END post_with_map_advanced_react]