// This snippet file was generated by processing the source file:
// ./firestore-react/test.solution-arrays.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START post_with_map_react]
// Sample document in the 'posts' collection
{
    title: "My great post",
    categories: {
        "technology": true,
        "opinion": true,
        "cats": true
    }
}
// [END post_with_map_react]