// This snippet file was generated by processing the source file:
// ./database-next/read-and-write.js
//
// To make edits to the snippets in this file, please edit the source

// [START rtdb_social_star_increment_modular]
function addStar(uid, key) {
  import { getDatabase, ServerValue } from "firebase/database";
  const db = getDatabase();

  const updates = {};
  updates[`posts/${key}/stars/${uid}`] = true;
  updates[`posts/${key}/starCount`] = ServerValue.increment(1);
  updates[`user-posts/${key}/stars/${uid}`] = true;
  updates[`user-posts/${key}/starCount`] = ServerValue.increment(1);
  db.ref().update(updates);
}
// [END rtdb_social_star_increment_modular]