// This snippet file was generated by processing the source file:
// ./auth-next/facebook.js
//
// To make edits to the snippets in this file, please edit the source

// / [START auth_facebook_provider_scopes_modular]
provider.addScope('user_birthday');
// [END auth_facebook_provider_scopes_modular]