// This snippet file was generated by processing the source file:
// ./auth-next/facebook.js
//
// To make edits to the snippets in this file, please edit the source

// [START auth_facebook_provider_params_modular]
provider.setCustomParameters({
  'display': 'popup'
});
// [END auth_facebook_provider_params_modular]