// This snippet file was generated by processing the source file:
// ./analytics-next/ecommerce.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START analytics_ecommerce_shipping_info_modular]
import { getAnalytics, logEvent } from "firebase/analytics";

// Prepare ecommerce params
const params8 = {
  currency: 'USD',
  value: 14.98, // Total Revenue
  coupon: 'SUMMER_FUN',
  shipping_tier: 'Ground',
  items: [item_jeggings]
};

// Log event
const analytics = getAnalytics();
logEvent(analytics, 'add_shipping_info', params8);
// [END analytics_ecommerce_shipping_info_modular]