// This snippet file was generated by processing the source file:
// ./auth-next/phone-auth.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START auth_get_recaptcha_response_modular]
const recaptchaResponse = grecaptcha.getResponse(recaptchaWidgetId);
// [END auth_get_recaptcha_response_modular]