// This snippet file was generated by processing the source file:
// ./auth-next/phone-auth.js
//
// To make edits to the snippets in this file, please edit the source

// [START auth_phone_recaptcha_verifier_simple_modular]
import { getAuth, RecaptchaVerifier } from "firebase/auth";

const auth = getAuth(firebaseApp);
window.recaptchaVerifier = new RecaptchaVerifier('recaptcha-container', {}, auth);
// [END auth_phone_recaptcha_verifier_simple_modular]