// This snippet file was generated by processing the source file:
// ./auth-react/emulator-suite.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START auth_emulator_google_credential_react]
import { getAuth, signInWithCredential, GoogleAuthProvider } from "firebase/auth";

function SignInButton() {
  async function signIn() {
    const auth = getAuth();
    await signInWithCredential(auth, GoogleAuthProvider.credential(
      '{"sub": "abc123", "email": "foo@example.com", "email_verified": true}'
    ));
  }

  return <button onClick={signIn}>Sign in with Google</button>;
}
// [END auth_emulator_google_credential_react]