// This snippet file was generated by processing the source file:
// ./functions-next/callable.js
//
// To make edits to the snippets in this file, please edit the source

// [START fb_functions_call_add_message_error_modular]
import { getFunctions, httpsCallable } from "firebase/functions";

const functions = getFunctions();
const addMessage = httpsCallable(functions, 'addMessage');
addMessage({ text: messageText })
  .then((result) => {
    // Read result of the Cloud Function.
    /** @type {any} */
    const data = result.data;
    const sanitizedMessage = data.text;
  })
  .catch((error) => {
    // Getting the Error details.
    const code = error.code;
    const message = error.message;
    const details = error.details;
    // ...
  });
// [END fb_functions_call_add_message_error_modular]