// This snippet file was generated by processing the source file:
// ./perf-next/index.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START perf_get_instance_modular]
import { getPerformance } from "firebase/performance";
const perf = getPerformance();
// [END perf_get_instance_modular]