// This snippet file was generated by processing the source file:
// ./perf-next/index.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START perf_imports_modular]
import { initializeApp } from "firebase/app";
import { getPerformance } from "firebase/performance";
// [END perf_imports_modular]