// This snippet file was generated by processing the source file:
// ./perf-next/index.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START perf_initialize_modular]
// TODO: Replace the following with your app's Firebase project configuration
// See: https://firebase.google.com/docs/web/setup#config-object
const firebaseConfig = {
  // ...
};

// Initialize Firebase
const app = initializeApp(firebaseConfig);

// Initialize Performance Monitoring and get a reference to the service
const perf = getPerformance(app);
// [END perf_initialize_modular]