// This snippet file was generated by processing the source file:
// ./perf-next/index.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START perf_singleton_modular]
// Initialize Performance Monitoring and get a reference to the service
const perf = getPerformance(app);
// [END perf_singleton_modular]