// This snippet file was generated by processing the source file:
// ./perf-next/index.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START perf_user_timing_marks_modular]
const performance = window.performance;

performance.mark("measurementStart");

// Code that you want to trace 
// ...

performance.mark("measurementStop");
performance.measure("customTraceName", "measurementStart", "measurementStop");
// [END perf_user_timing_marks_modular]