// This snippet file was generated by processing the source file:
// ./perf-next/index.js
//
// To make edits to the snippets in this file, please edit the source

// [START perf_get_instance_modular]
import { getPerformance } from "firebase/performance";
const perf = getPerformance(firebaseApp);
// [END perf_get_instance_modular]