// This snippet file was generated by processing the source file:
// ./firestore-next/test.solution-counters.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START create_counter_modular]
function createCounter(ref, num_shards) {
    import { doc, writeBatch } from "firebase/firestore";

    const batch = writeBatch(db);

    // Initialize the counter document
    batch.set(ref, { num_shards: num_shards });

    // Initialize each shard with count=0
    for (let i = 0; i < num_shards; i++) {
        const shardRef = doc(ref, 'shards', i.toString());
        batch.set(shardRef, { count: 0 });
    }

    // Commit the write batch
    return batch.commit();
}
// [END create_counter_modular]