// This snippet file was generated by processing the source file:
// snippets/firestore-next/test-solution-counters/get_count.js
//
// To make edits to the snippets in this file, please edit the source

// [START modular_get_count]
async function getCount(ref) {
    import { collection, getDocs } from "@firebase/firestore";

    // Sum the count of each shard in the subcollection
    const snapshot = await getDocs(collection(ref, 'shards'));

    let totalCount = 0;
    snapshot.forEach(doc => {
        totalCount += doc.data().count;
    });

    return totalCount;
}
// [END modular_get_count]