// This snippet file was generated by processing the source file:
// ./auth-next/yahoo-oauth.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START auth_yahoo_provider_create_modular]
import { OAuthProvider } from "firebase/auth";

const provider = new OAuthProvider('yahoo.com');
// [END auth_yahoo_provider_create_modular]