// This snippet file was generated by processing the source file:
// ./auth-next/yahoo-oauth.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START auth_yahoo_provider_params_modular]
provider.setCustomParameters({
  // Prompt user to re-authenticate to Yahoo.
  prompt: 'login',
  // Localize to French.
  language: 'fr'
});  
// [END auth_yahoo_provider_params_modular]