// This snippet file was generated by processing the source file:
// ./auth-next/yahoo-oauth.js
//
// To make edits to the snippets in this file, please edit the source

// [START auth_yahoo_signin_popup_modular]
import { getAuth, signInWithPopup } from "firebase/auth";

const auth = getAuth();
signInWithPopup(auth, provider)
  .then((result) => {
    // User is signed in.
    // IdP data available in result.additionalUserInfo.profile.
    // Yahoo OAuth access token can be retrieved by calling:
    // result.credential.accessToken
    // Yahoo OAuth ID token can be retrieved by calling:
    // result.credential.idToken
  })
  .catch((error) => {
    // Handle error.
  });
// [END auth_yahoo_signin_popup_modular]