// This snippet file was generated by processing the source file:
// ./auth-next/yahoo-oauth.js
//
// To make edits to the snippets in this file, please edit the source

// [START auth_yahoo_signin_redirect_modular]
import { getAuth, signInWithRedirect } from "firebase/auth";

const auth = getAuth(firebaseApp);
signInWithRedirect(auth, provider);
// [END auth_yahoo_signin_redirect_modular]