// This snippet file was generated by processing the source file:
// ./auth-react/multi-tenancy.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START multitenant_send_emaillink_react]
import { useActionState } from "react";
import { sendSignInLinkToEmail } from "firebase/auth";

function SendSignInLinkForm() {
  const [error, sendLink, isPending] = useActionState(async (previousError, formData) => {
    const email = formData.get("email");
    // Switch to TENANT_ID1
    auth.tenantId = 'TENANT_ID1';

    try {
      await sendSignInLinkToEmail(auth, email, actionCodeSettings);
      // The link was successfully sent. Inform the user.
      // Save the email locally so you don't need to ask the user for it again
      // if they open the link on the same device.
      window.localStorage.setItem('emailForSignIn', email);
      return null;
    } catch (error) {
      // Handle / display error.
      // ...
      return error.message;
    }
  }, null);

  return (
    <form action={sendLink}>
      <input name="email" type="email" />
      <button type="submit" disabled={isPending}>Send sign-in link</button>
      {error ? <p>{error}</p> : null}
    </form>
  );
}
// [END multitenant_send_emaillink_react]