// This snippet file was generated by processing the source file:
// ./auth-react/multi-tenancy.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START multitenant_signin_password_react]
import { useActionState } from "react";
import { signInWithEmailAndPassword } from "firebase/auth";

function SignInForm() {
  const [error, signIn, isPending] = useActionState(async (previousError, formData) => {
    auth.tenantId = 'TENANT_ID';

    try {
      const userCredential = await signInWithEmailAndPassword(auth, formData.get("email"), formData.get("password"));
      // User is signed in.
      // userCredential.user.tenantId is 'TENANT_ID'.
      return null;
    } catch (error) {
      // Handle / display error.
      // ...
      return error.message;
    }
  }, null);

  return (
    <form action={signIn}>
      <input name="email" type="email" />
      <input name="password" type="password" />
      <button type="submit" disabled={isPending}>Sign in</button>
      {error ? <p>{error}</p> : null}
    </form>
  );
}
// [END multitenant_signin_password_react]