// This snippet file was generated by processing the source file:
// ./auth-react/multi-tenancy.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START multitenant_signin_custom_token_react]
import { signInWithCustomToken } from "firebase/auth";

function SignInButton({ token }) {
  async function signIn() {
    auth.tenantId = 'TENANT_ID1';

    try {
      await signInWithCustomToken(auth, token);
    } catch (error) {
      // Handle / display error.
      // ...
    }
  }

  return <button onClick={signIn}>Sign in</button>;
}
// [END multitenant_signin_custom_token_react]