// This snippet file was generated by processing the source file:
// ./auth-react/multi-tenancy.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START multitenant_set_tenant_react]
import { getAuth } from "firebase/auth";
const auth = getAuth();
const tenantId = "TENANT_ID1";
auth.tenantId = tenantId;
// [END multitenant_set_tenant_react]