// This snippet file was generated by processing the source file:
// ./auth-react/multi-tenancy.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START multitenant_signin_password_demo_react]
import { useEffect, useState } from "react";
import { signInWithEmailAndPassword, onAuthStateChanged } from "firebase/auth";

function SignInForm() {
  const [user, setUser] = useState(null);

  async function signIn(formData) {
    // Switch to TENANT_ID1
    auth.tenantId = 'TENANT_ID1';

    // Sign in with tenant
    const userCredential = await signInWithEmailAndPassword(auth, formData.get("email"), formData.get("password"));
    // User is signed in.
    const user = userCredential.user;
    // user.tenantId is set to 'TENANT_ID1'.
    // Switch to 'TENANT_ID2'.
    auth.tenantId = 'TENANT_ID2';
    // auth.currentUser still points to the user.
    // auth.currentUser.tenantId is 'TENANT_ID1'.
  }

  // You could also get the current user from Auth state observer.
  useEffect(() => {
    // onAuthStateChanged returns an unsubscribe function. Returning it from the
    // effect detaches the listener when the component unmounts.
    return onAuthStateChanged(auth, (user) => {
      setUser(user);
    });
  }, []);

  return user ? (
    // User is signed in.
    // user.tenantId is set to 'TENANT_ID1'.
    <p>{user.tenantId}</p>
  ) : (
    // No user is signed in.
    <form action={signIn}>
      <input name="email" type="email" />
      <input name="password" type="password" />
      <button type="submit">Sign in</button>
    </form>
  );
}
// [END multitenant_signin_password_demo_react]