// This snippet file was generated by processing the source file:
// ./auth-react/microsoft-oauth.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START auth_msft_signin_popup_react]
import { getAuth, signInWithPopup, OAuthProvider } from "firebase/auth";

function SignInButton() {
  async function signIn() {
    const auth = getAuth();
    try {
      const result = await signInWithPopup(auth, provider);
      // User is signed in.
      // IdP data available in result.additionalUserInfo.profile.

      // Get the OAuth access token and ID Token
      const credential = OAuthProvider.credentialFromResult(result);
      const accessToken = credential.accessToken;
      const idToken = credential.idToken;
    } catch (error) {
      // Handle error.
    }
  }

  return <button onClick={signIn}>Sign in with Microsoft</button>;
}
// [END auth_msft_signin_popup_react]