// This snippet file was generated by processing the source file:
// ./auth-react/microsoft-oauth.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START auth_msft_link_popup_react]
import { useTransition } from "react";
import { getAuth, linkWithPopup, OAuthProvider } from "firebase/auth";

function LinkButton() {
  const [isPending, startTransition] = useTransition();

  function link() {
    startTransition(async () => {
      const provider = new OAuthProvider('microsoft.com');
      const auth = getAuth();

      try {
        const result = await linkWithPopup(auth.currentUser, provider);
        // Microsoft credential is linked to the current user.
        // IdP data available in result.additionalUserInfo.profile.

        // Get the OAuth access token and ID Token
        const credential = OAuthProvider.credentialFromResult(result);
        const accessToken = credential.accessToken;
        const idToken = credential.idToken;
      } catch (error) {
        // Handle error.
      }
    });
  }

  return <button onClick={link} disabled={isPending}>Link Microsoft</button>;
}
// [END auth_msft_link_popup_react]