// This snippet file was generated by processing the source file:
// ./auth-react/microsoft-oauth.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START auth_msft_provider_scopes_react]
provider.addScope('mail.read');
provider.addScope('calendars.read');
// [END auth_msft_provider_scopes_react]