// This snippet file was generated by processing the source file:
// ./firestore-next/emulator-suite.js
//
// To make edits to the snippets in this file, please edit the source

// [START fs_emulator_connect_modular]
import { initializeFirestore } from "firebase/firestore";

let settings = {};
if (location.hostname === "localhost") {
  settings = {
    host: "localhost:8080",
    ssl: false
  };
}

// firebaseApps previously initialized using initializeApp()
const db = initializeFirestore(firebaseApp, settings);
// [END fs_emulator_connect_modular]