// This snippet file was generated by processing the source file:
// ./auth-next/email-link-auth.js
//
// To make edits to the snippets in this file, please edit the source

// [START auth_email_link_send_modular]
import { getAuth, sendSignInLinkToEmail } from "firebase/auth";

const auth = getAuth(firebaseApp);
sendSignInLinkToEmail(auth, email, actionCodeSettings)
  .then(() => {
    // The link was successfully sent. Inform the user.
    // Save the email locally so you don't need to ask the user for it again
    // if they open the link on the same device.
    window.localStorage.setItem('emailForSignIn', email);
    // ...
  })
  .catch((error) => {
    const errorCode = error.code;
    const errorMessage = error.message;
    // ...
  });
// [END auth_email_link_send_modular]