// This snippet file was generated by processing the source file:
// ./firestore-next/test.firestore.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START aggregate_data_modular]
await setDoc(doc(collection(db, "cities"), "SF"), {name: "San Francisco", state: "CA", country: "USA", population: 870000});
await setDoc(doc(collection(db, "cities"), "LA"), {name: "Los Angeles", state: "CA", country: "USA", population: 3970000});
await setDoc(doc(collection(db, "cities"), "NY"), {name: "New York", state: "NY", country: "USA", population: 8530000});
await setDoc(doc(collection(db, "cities"), "TOR"), {name: "Toronto", state: null, country: "Canada", population: 2930000});
await setDoc(doc(collection(db, "cities"), "MEX"), {name: "Mexico City", state: null, country: "Mexico", population: 9200000});
// [END aggregate_data_modular]