// This snippet file was generated by processing the source file:
// ./firestore-next/test.firestore.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START aggregate_distinct_modular]
const results = await db.pipeline()
  .collection("books")
  .distinct([
    field("author").toUpper().as("author"),
    field("genre")
  ])
  .execute();
// [END aggregate_distinct_modular]