// This snippet file was generated by processing the source file:
// ./firestore-next/test.firestore.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START aggregate_without_group_modular]
const cities = await execute(db.pipeline()
  .collection("cities")
  .aggregate(
      countAll().as("total"),
      average("population").as("averagePopulation")
  ));
// [END aggregate_without_group_modular]