// This snippet file was generated by processing the source file:
// ./firestore-next/test.firestore.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START array_contains_any_modular]
const result = await db.pipeline()
  .collection("books")
  .select([
    field("genre")
      .arrayContainsAny([constant("fantasy"), constant("nonfiction")])
      .as("isMysteryOrFantasy")
  ])
  .execute();
// [END array_contains_any_modular]