// This snippet file was generated by processing the source file:
// snippets/firestore-next/test-firestore/cities_document_set.js
//
// To make edits to the snippets in this file, please edit the source

// [START modular_cities_document_set]
import { collection, doc, setDoc } from "firebase/firestore"; 

await setDoc(doc(collection(db, "cities"), "new-city-id"), data);
// [END modular_cities_document_set]