// This snippet file was generated by processing the source file:
// ./firestore-next/test.firestore.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START collection_input_data_modular]
await setDoc(doc(collection(db, "cities"), "SF"), {name: "San Francsico", state: "California"});
await setDoc(doc(collection(db, "cities"), "NYC"), {name: "New York City", state: "New York"});
await setDoc(doc(collection(db, "cities"), "CHI"), {name: "Chicago", state: "Illinois"});
await setDoc(doc(collection(db, "states"), "CA"), {name: "California"});
// [END collection_input_data_modular]