// This snippet file was generated by processing the source file:
// ./firestore-next/test.firestore.js
//
// To make edits to the snippets in this file, please edit the source

// [START collection_reference_modular]
import { collection } from "firebase/firestore";

const usersCollectionRef = collection(db, 'users');
// [END collection_reference_modular]