// This snippet file was generated by processing the source file:
// ./firestore-next/test.firestore.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START collection_group_input_modular]
const results = await execute(db.pipeline()
  .collectionGroup("departments")
  .sort(field("employees").ascending()));
// [END collection_group_input_modular]