// This snippet file was generated by processing the source file:
// ./firestore-next/test.firestore.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START count_function_modular]
// Total number of books in the collection
const countOfAll = await db.pipeline()
  .collection("books")
  .aggregate([countAll().as("count")])
  .execute();

// Number of books with nonnull `ratings` field
const countField = await db.pipeline()
  .collection("books")
  .aggregate([field("ratings").count().as("count")])
  .execute();
// [END count_function_modular]