// This snippet file was generated by processing the source file:
// ./firestore-next/test.firestore.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START database_input_modular]
const results = await execute(db.pipeline()
  .database()
  .sort(field("population").ascending()));
// [END database_input_modular]