// This snippet file was generated by processing the source file:
// ./firestore-next/test.firestore.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START database_input_data_modular]
await setDoc(doc(collection(db, "cities"), "SF"), {name: "San Francsico", state: "California", population: 800000});
await setDoc(doc(collection(db, "states"), "CA"), {name: "California", population: 39000000});
await setDoc(doc(collection(db, "countries"), "USA"), {name: "United States of America", population: 340000000});
// [END database_input_data_modular]