// This snippet file was generated by processing the source file:
// ./firestore-next/test.firestore.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START distinct_example_modular]
const cities = await execute(db.pipeline()
  .collection("cities")
  .distinct("country"));
// [END distinct_example_modular]