// This snippet file was generated by processing the source file:
// snippets/firestore-next/test-firestore/doc_reference.js
//
// To make edits to the snippets in this file, please edit the source

// [START modular_doc_reference]
import { collection, doc } from "firebase/firestore";

const alovelaceDocumentRef = doc(collection(db, 'users'), 'alovelace');
// [END modular_doc_reference]