// This snippet file was generated by processing the source file:
// ./firestore-next/test.firestore.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START document_input_modular]
const results = await execute(db.pipeline()
  .documents([
    doc(collection(db, "cities"), "SF"),
    doc(collection(db, "cities"), "NYC")])
  .sort(field("name").ascending()));
// [END document_input_modular]