// This snippet file was generated by processing the source file:
// snippets/firestore-next/test-firestore/enable_network.js
//
// To make edits to the snippets in this file, please edit the source

// [START modular_enable_network]
import { enableNetwork } from "firebase/firestore"; 

await enableNetwork(db)
// Do online actions
// [START_EXCLUDE]
console.log("Network enabled!");
// [END_EXCLUDE]
// [END modular_enable_network]