// This snippet file was generated by processing the source file:
// ./firestore-next/test.firestore.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START euclidean_distance_modular]
const sampleVector = [0.0, 1, 2, 3, 4, 5];
const result = await db.pipeline()
  .collection("books")
  .select([
    field("embedding").euclideanDistance(sampleVector).as("euclideanDistance")
  ])
  .execute();
// [END euclidean_distance_modular]