// This snippet file was generated by processing the source file:
// ./firestore-next/test.firestore.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START four_disjunctions_compact_modular]
query(collectionRef,
  and( or( where("a", "==", 1), where("b", "==", 2) ),
       or( where("c", "==", 3), where("d", "==", 4) )
  )
);
// [END four_disjunctions_compact_modular]