// This snippet file was generated by processing the source file:
// ./firestore-next/test.firestore.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START full_replace_modular]
const names = await db.pipeline()
  .collection("cities")
  .replace(field("location"))
  .execute();
// [END full_replace_modular]