// This snippet file was generated by processing the source file:
// snippets/firestore-next/test-firestore/get_multiple_all.js
//
// To make edits to the snippets in this file, please edit the source

// [START modular_get_multiple_all]
import { collection, getDocs } from "firebase/firestore";

const querySnapshot = await getDocs(collection(db, "cities"));
querySnapshot.forEach((doc) => {
  // doc.data() is never undefined for query doc snapshots
  console.log(doc.id, " => ", doc.data());
});
// [END modular_get_multiple_all]