// This snippet file was generated by processing the source file:
// ./firestore-next/test.firestore.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START is_nan_modular]
const result = await db.pipeline()
  .collection("books")
  .select([
    field("rating").isNan().as("hasInvalidRating")
  ])
  .execute();
// [END is_nan_modular]