// This snippet file was generated by processing the source file:
// ./firestore-next/test.firestore.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START is_not_nan_modular]
const result = await db.pipeline()
  .collection("books")
  .select([
    field("rating").isNotNan().as("hasValidRating")
  ])
  .execute();
// [END is_not_nan_modular]