// This snippet file was generated by processing the source file:
// ./firestore-next/test.firestore.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START less_or_equal_modular]
const result = await db.pipeline()
  .collection("books")
  .select([field("rating").lessThanOrEqual(2).as("hasBadRating")])
  .execute();
// [END less_or_equal_modular]