// This snippet file was generated by processing the source file:
// ./firestore-next/test.firestore.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START map_merge_overwrite_modular]
// unsupported in client SDKs for now
// [END map_merge_overwrite_modular]