// This snippet file was generated by processing the source file:
// ./firestore-next/test.firestore.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START not_function_modular]
const result = await db.pipeline()
  .collection("books")
  .select([
    (field("tags").arrayContains("nonfiction").not())
      .as("isFiction")
  ])
  .execute();
// [END not_function_modular]