// This snippet file was generated by processing the source file:
// ./firestore-next/test.firestore.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START or_function_modular]
const result = await db.pipeline()
  .collection("books")
  .select([
    or(field("genre").equal("Fantasy"), (field("tags").arrayContains("adventure")))
      .as("matchesSearchFilters")
  ])
  .execute();
// [END or_function_modular]