// This snippet file was generated by processing the source file:
// snippets/firestore-next/test-firestore/order_and_start.js
//
// To make edits to the snippets in this file, please edit the source

// [START modular_order_and_start]
import { query, orderBy, startAt } from "firebase/firestore";  

const q = query(citiesRef, orderBy("population"), startAt(1000000));
// [END modular_order_and_start]