// This snippet file was generated by processing the source file:
// ./firestore-next/test.firestore.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START pipeline_initialization_modular]
import { getFirestore } from "@firebase/firestore";
import { execute } from "@firebase/firestore/pipelines";
const database = getFirestore(app, "enterprise");
const pipeline = database.pipeline();
// [END pipeline_initialization_modular]