// This snippet file was generated by processing the source file:
// ./firestore-next/test.firestore.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START remove_fields_nested_data_modular]
await setDoc(doc(collection(db, "cities"), "SF"), {
  name: "San Francisco", location: {country: "USA", state: "California"}
});
await setDoc(doc(collection(db, "cities"), "TO"), {
  name: "Toronto", location: {country: "Canada", province: "Ontario"}
});
// [END remove_fields_nested_data_modular]