// This snippet file was generated by processing the source file:
// ./firestore-next/test.firestore.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START remove_fields_nested_modular]
const results = await execute(db.pipeline()
  .collection("cities")
  .removeFields("location.state"));
// [END remove_fields_nested_modular]