// This snippet file was generated by processing the source file:
// ./firestore-next/test.firestore.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START reverse_function_modular]
field("tags").reverse();
// [END reverse_function_modular]