// This snippet file was generated by processing the source file:
// ./firestore-next/test.firestore.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START search_exclude_term_data_modular]
await addDoc(collection(db, "Restaurants"), {
  "name": "City Coffee",
  "description": "Premium coffee and pastries."
});
// [END search_exclude_term_data_modular]