// This snippet file was generated by processing the source file:
// ./firestore-next/test.firestore.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START search_exact_match_data_modular]
await addDoc(collection(db, "Restaurants"), {
  "name": "Waffle Place",
  "description": "A cozy place for fresh waffles."
});
// [END search_exact_match_data_modular]