// This snippet file was generated by processing the source file:
// ./firestore-next/test.firestore.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START select_syntax_modular]
const names = await execute(db.pipeline()
  .collection("cities")
  .select(
    field("name").stringConcat(", ", field("location.country")).as("name"),
    "population"
  ));
// [END select_syntax_modular]