// This snippet file was generated by processing the source file:
// ./firestore-next/test.firestore.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START select_position_modular]
const names = await execute(db.pipeline()
  .collection("cities")
  .where(field("location.country").equal("Canada"))
  .select(
    field("name").stringConcat(", ", field("location.country")).as("name"),
    "population"));
// [END select_position_modular]