// This snippet file was generated by processing the source file:
// ./firestore-next/test.firestore.js
//
// To make edits to the snippets in this file, please edit the source

// [START set_document_modular]
import { doc, collection, setDoc } from "firebase/firestore"; 

// Add a new document in collection "cities"
await setDoc(doc(collection(db, "cities"), "LA"), {
  name: "Los Angeles",
  state: "CA",
  country: "USA"
});
// [END set_document_modular]