// This snippet file was generated by processing the source file:
// ./firestore-next/test.firestore.js
//
// To make edits to the snippets in this file, please edit the source

// [START set_custom_object_modular]
import { doc, collection, setDoc } from "firebase/firestore"; 

// Set with cityConverter
const ref = doc(collection(db, "cities"), "LA").withConverter(cityConverter);
await setDoc(ref, new City("Los Angeles", "CA", "USA"));
// [END set_custom_object_modular]