// This snippet file was generated by processing the source file:
// ./firestore-next/test.firestore.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START sort_document_id_modular]
const results = await execute(db.pipeline()
  .collection("cities")
  .sort(field("country").ascending(), field("__name__").ascending()));
// [END sort_document_id_modular]