// This snippet file was generated by processing the source file:
// ./firestore-next/test.firestore.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START starts_with_modular]
const result = await db.pipeline()
  .collection("books")
  .select([
    field("title").startsWith("The")
      .as("needsSpecialAlphabeticalSort")
  ])
  .execute();
// [END starts_with_modular]