// This snippet file was generated by processing the source file:
// ./firestore-next/test.firestore.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START string_contains_modular]
const result = await db.pipeline()
  .collection("articles")
  .select([
    field("body").stringContains("Firestore")
      .as("isFirestoreRelated")
  ])
  .execute();
// [END string_contains_modular]