// This snippet file was generated by processing the source file:
// ./firestore-next/test.firestore.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START subcollection_input_data_modular]
await setDoc(doc(collection(db, "cities/SF/departments"), "building"),
  {name: "SF Building Deparment", employees: 750});
await setDoc(doc(collection(db, "cities/NY/departments"), "building"),
  {name: "NY Building Deparment", employees: 1000});
await setDoc(doc(collection(db, "cities/CHI/departments"), "building"),
  {name: "CHI Building Deparment", employees: 900});
await setDoc(doc(collection(db, "cities/NY/departments"), "finance"),
  {name: "NY Finance Deparment", employees: 1200});
// [END subcollection_input_data_modular]