// This snippet file was generated by processing the source file:
// ./firestore-next/test.firestore.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START subtract_function_modular]
const storeCredit = 7;
const result = await db.pipeline()
  .collection("books")
  .select([field("price").subtract(constant(storeCredit)).as("totalCost")])
  .execute();
// [END subtract_function_modular]