// This snippet file was generated by processing the source file:
// ./firestore-next/test.firestore.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START timestamp_add_modular]
const result = await db.pipeline()
  .collection("documents")
  .select([
    field("createdAt").timestampAdd("day", 3653).as("expiresAt")
  ])
  .execute();
// [END timestamp_add_modular]