// This snippet file was generated by processing the source file:
// ./firestore-next/test.firestore.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START timestamp_unix_micros_modular]
const result = await db.pipeline()
  .collection("documents")
  .select([
    field("dateString").timestampToUnixMicros().as("unixMicros")
  ])
  .execute();
// [END timestamp_unix_micros_modular]