// This snippet file was generated by processing the source file:
// ./firestore-next/test.firestore.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START to_scalar_expression_modular]
const result = await execute(db.pipeline().collection("authors")
    .define(
        field("id").as("currentAuthorId")
    )
    .addFields(
        db.pipeline().collection("books")
            .where(field("author_id").equal(variable("currentAuthorId")))
            .aggregate(
                field("rating").average().as("avgRating")
            )
            .toScalarExpression()
            .as("averageBookRating")
    ));
// [END to_scalar_expression_modular]