// This snippet file was generated by processing the source file:
// ./firestore-next/test.firestore.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START to_upper_modular]
const result = await db.pipeline()
  .collection("authors")
  .select([
    field("name").toUpper()
      .as("uppercaseName")
  ])
  .execute();
// [END to_upper_modular]