// This snippet file was generated by processing the source file:
// ./firestore-next/test.firestore.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START two_disjunctions_modular]
query(collectionRef, or( where("a", "==", 1), where("b", "==", 2) ));
// [END two_disjunctions_modular]