// This snippet file was generated by processing the source file:
// ./firestore-next/test.firestore.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START unnest_alias_index_modular]
const userScore = await execute(db.pipeline()
  .collection("users")
  .unnest(field("scores").as("userScore"), /* index_field= */ "attempt"));
// [END unnest_alias_index_modular]