// This snippet file was generated by processing the source file:
// ./firestore-next/test.firestore.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START unnest_preserve_empty_array_modular]
const userScore = await execute(db.pipeline()
  .collection("users")
  .unnest(
    conditional(
      field("scores").equal(array([])),
      array([field("scores")]),
      field("scores")
    ).as("userScore"),
  /* index_field= */ "attempt"));
// [END unnest_preserve_empty_array_modular]