// This snippet file was generated by processing the source file:
// ./firestore-next/test.firestore.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START unnest_stage_modular]
const results = await execute(db.pipeline()
  .database()
  .unnest(field("arrayField").as("unnestedArrayField"), "index")
);
// [END unnest_stage_modular]