// This snippet file was generated by processing the source file:
// ./firestore-next/test.firestore.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START unnest_empty_array_data_modular]
await addDoc(collection(db, "users"), {name: "foo", scores: [5, 4]});
await addDoc(collection(db, "users"), {name: "bar", scores: []});
// [END unnest_empty_array_data_modular]