// This snippet file was generated by processing the source file:
// snippets/firestore-next/test-firestore/update_document_array.js
//
// To make edits to the snippets in this file, please edit the source

// [START modular_update_document_array]
import { collection, doc, updateDoc, arrayUnion, arrayRemove } from "firebase/firestore";

const washingtonRef = doc(collection(db, "cities"), "DC");

// Atomically add a new region to the "regions" array field.
await updateDoc(washingtonRef, {
    regions: arrayUnion("greater_virginia")
});

// Atomically remove a region from the "regions" array field.
await updateDoc(washingtonRef, {
    regions: arrayRemove("east_coast")
});
// [END modular_update_document_array]