// This snippet file was generated by processing the source file:
// ./firestore-next/test.firestore.js
//
// To make edits to the snippets in this file, please edit the source

// [START update_document_modular]
import { collection, doc, updateDoc } from "firebase/firestore";

const washingtonRef = doc(collection(db, "cities"), "DC");

// Set the "capital" field of the city 'DC'
await updateDoc(washingtonRef, {
  capital: true
});
// [END update_document_modular]