// This snippet file was generated by processing the source file:
// ./firestore-next/test.firestore.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START vector_length_modular]
const result = await db.pipeline()
  .collection("books")
  .select([
    field("embedding").vectorLength().as("vectorLength")
  ])
  .execute();
// [END vector_length_modular]