// This snippet file was generated by processing the source file:
// ./firestore-next/test.firestore.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START xor_function_modular]
const result = await db.pipeline()
  .collection("books")
  .select([
    xor(field("tags").arrayContains("magic"), (field("tags").arrayContains("nonfiction")))
      .as("matchesSearchFilters")
  ])
  .execute();
// [END xor_function_modular]