// This snippet file was generated by processing the source file:
// ./database-react/offline.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START rtdb_detect_connection_state_react]
import { useEffect, useState } from "react";
import { getDatabase, ref, onValue } from "firebase/database";

function ConnectionState() {
  const [connected, setConnected] = useState(false);

  useEffect(() => {
    const db = getDatabase();
    const connectedRef = ref(db, ".info/connected");
    // onValue returns an unsubscribe function. Returning it from the effect
    // detaches the listener when the component unmounts.
    return onValue(connectedRef, (snap) => {
      if (snap.val() === true) {
        console.log("connected");
        setConnected(true);
      } else {
        console.log("not connected");
        setConnected(false);
      }
    });
  }, []);

  return <span>{connected ? "connected" : "not connected"}</span>;
}
// [END rtdb_detect_connection_state_react]