// This snippet file was generated by processing the source file:
// ./database-react/offline.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START rtdb_estimate_clock_skew_react]
import { useEffect, useState } from "react";
import { getDatabase, ref, onValue } from "firebase/database";

function EstimatedServerTime() {
  const [estimatedServerTimeMs, setEstimatedServerTimeMs] = useState(null);

  useEffect(() => {
    const db = getDatabase();
    const offsetRef = ref(db, ".info/serverTimeOffset");
    // onValue returns an unsubscribe function. Returning it from the effect
    // detaches the listener when the component unmounts.
    return onValue(offsetRef, (snap) => {
      const offset = snap.val();
      const estimatedServerTimeMs = new Date().getTime() + offset;
      setEstimatedServerTimeMs(estimatedServerTimeMs);
    });
  }, []);

  return <span>{estimatedServerTimeMs}</span>;
}
// [END rtdb_estimate_clock_skew_react]