// This snippet file was generated by processing the source file:
// ./storage-react/delete-files.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START storage_delete_file_react]
import { getStorage, ref, deleteObject } from "firebase/storage";

function DeleteFileButton() {
  async function deleteFile() {
    const storage = getStorage();

    // Create a reference to the file to delete
    const desertRef = ref(storage, 'images/desert.jpg');

    // Delete the file
    try {
      await deleteObject(desertRef);
      // File deleted successfully
    } catch (error) {
      // Uh-oh, an error occurred!
    }
  }

  return <button onClick={deleteFile}>Delete</button>;
}
// [END storage_delete_file_react]