// This snippet file was generated by processing the source file:
// ./auth-react/apple.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START auth_apple_provider_scopes_react]
provider.addScope('email');
provider.addScope('name');
// [END auth_apple_provider_scopes_react]