// This snippet file was generated by processing the source file:
// ./remoteconfig-react/index.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START rc_fetch_config_callback_react]
import { use, Suspense } from "react";
import { fetchAndActivate, getValue } from "firebase/remote-config";

// Start the fetch once, at module scope, so every render reuses the same promise.
const activation = fetchAndActivate(remoteConfig)
  .catch((err) => {
    // ...
  });

function WelcomeMessage() {
  use(activation);
  const val = getValue(remoteConfig, "welcome_message");
  return <p>{val.asString()}</p>;
}

function App() {
  return (
    <Suspense fallback={<p>Loading...</p>}>
      <WelcomeMessage />
    </Suspense>
  );
}
// [END rc_fetch_config_callback_react]