// This snippet file was generated by processing the source file:
// ./remoteconfig-react/index.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START rc_get_instance_react]
import { getRemoteConfig } from "firebase/remote-config";

const remoteConfig = getRemoteConfig();
// [END rc_get_instance_react]