// This snippet file was generated by processing the source file:
// ./remoteconfig-react/index.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START rc_set_minimum_fetch_time_react]
// The default and recommended production fetch interval for Remote Config is 12 hours
remoteConfig.settings.minimumFetchIntervalMillis = 3600000;
// [END rc_set_minimum_fetch_time_react]