// This snippet file was generated by processing the source file:
// ./firestore-react/test.solution-counters.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START get_count_react]
import { useEffect, useState } from "react";
import { collection, getDocs } from "firebase/firestore";

function TotalCount({ counterRef }) {
    const [totalCount, setTotalCount] = useState(null);

    useEffect(() => {
        let ignore = false;
        // Sum the count of each shard in the subcollection
        getDocs(collection(counterRef, 'shards')).then((snapshot) => {
            if (ignore) return;
            let totalCount = 0;
            snapshot.forEach((doc) => {
                totalCount += doc.data().count;
            });

            setTotalCount(totalCount);
        });
        // Ignore the result if counterRef changes before the read completes.
        return () => { ignore = true; };
    }, [counterRef]);

    return <span>{totalCount}</span>;
}
// [END get_count_react]