// [SNIPPET_REGISTRY disabled]

import * as cp from "child_process";
import * as fs from "fs";
import * as path from "path";

// Regex for comment which must be included in a file for it to be separated
const RE_SNIPPETS_SEPARATION = /\[SNIPPETS_SEPARATION\s+enabled\]/;

// Regex for comment to control the separator suffix
const RE_SNIPPETS_SUFFIX = /\[SNIPPETS_SUFFIX\s+([A-Za-z0-9_]+)\]/;

// Regex for [START] and [END] snippet tags.
const RE_START_SNIPPET = /\[START\s+([A-Za-z_]+)\s*\]/;
const RE_END_SNIPPET = /\[END\s+([A-Za-z_]+)\s*\]/;

// Regex for const = require statements
// TODO: Handle multiline imports?
const RE_REQUIRE = /const {(.+?)} = require\((.+?)\)/;

type SnippetsConfig = {
  enabled: boolean;
  suffix: string;
  map: Record<string, string[]>;
};

const DEFAULT_SUFFIX = "_modular";

function isBlank(line: string) {
  return line.trim().length === 0;
}

/**
 * Turns a series of source lines into a standalone snippet file by:
 *   - Converting require statements into top-level imports.
 *   - Adjusting indentation to left-align all content
 *   - Removing any blank lines at the starts
 *   - Adding a suffix to snippet names
 *
 * @param lines the lines containing the snippet (including START/END comments)
 * @param sourceFile the source file where the original snippet lives
 * @param snippetSuffix the suffix (such as _modular)
 */
function processSnippet(
  lines: string[],
  sourceFile: string,
  snippetSuffix: string
): string {
  const outputLines: string[] = [];

  for (const line of lines) {
    if (line.match(RE_REQUIRE)) {
      outputLines.push(line.replace(RE_REQUIRE, `import {$1} from $2`));
    } else if (line.match(RE_START_SNIPPET)) {
      outputLines.push(line.replace(RE_START_SNIPPET, `[START $1${snippetSuffix}]`));
    } else if (line.match(RE_END_SNIPPET)) {
      outputLines.push(
        line.replace(RE_END_SNIPPET, `[END $1${snippetSuffix}]`)
      );
    } else {
      outputLines.push(line);
    }
  }

  // Adjust indentation of the otherLines so that they're left aligned
  const nonBlankLines = outputLines.filter((l) => !isBlank(l));
  const indentSizes = nonBlankLines.map((l) => l.length - l.trimLeft().length);
  const minIndent = Math.min(...indentSizes);

  const adjustedOutputLines: string[] = [];
  for (const line of outputLines) {
    if (isBlank(line)) {
      adjustedOutputLines.push("");
    } else {
      adjustedOutputLines.push(line.substr(minIndent));
    }
  }

  // Special case: if the first line after the comments is blank we want to remove it
  const firstNonComment = adjustedOutputLines.findIndex(
    (l) => !l.startsWith("//")
  );
  if (isBlank(outputLines[firstNonComment])) {
    adjustedOutputLines.splice(firstNonComment, 1);
  }

  const preambleLines = [
    `// This snippet file was generated by processing the source file:`,
    `// ${sourceFile}`,
    `//`,
    `// To make edits to the snippets in this file, please edit the source`,
    ``,
  ];
  const content = [...preambleLines, ...adjustedOutputLines].join("\n");
  return content;
}

/**
 * Lists all the files in this repository that should be checked for snippets
 */
function listSnippetFiles(): string[] {
  const output = cp
    .execSync(
      'find . -type f -name "*.js" -not -path "*node_modules*" -not -path "./snippets*"'
    )
    .toString();
  return output.split("\n").filter((x) => !isBlank(x));
}

/**
 * Collect all the snippets from a file into a map of snippet name to lines.
 * @param filePath the file path to read.
 */
function collectSnippets(filePath: string): SnippetsConfig {
  const fileContents = fs.readFileSync(filePath).toString();
  const lines = fileContents.split("\n");

  const config: SnippetsConfig = {
    enabled: false,
    suffix: DEFAULT_SUFFIX,
    map: {},
  };

  config.enabled = lines.some((l) => !!l.match(RE_SNIPPETS_SEPARATION));
  if (!config.enabled) {
    return config;
  }

  const suffixLine = lines.find((l) => !!l.match(RE_SNIPPETS_SUFFIX));
  if (suffixLine) {
    const m = suffixLine.match(RE_SNIPPETS_SUFFIX);
    config.suffix = m[1];
  }

  let inSnippetNames = [];

  for (const line of lines) {
    const startMatch = line.match(RE_START_SNIPPET);
    const endMatch = line.match(RE_END_SNIPPET);

    if (startMatch) {
      const snippetName = startMatch[1];
      config.map[snippetName] = [];
      config.map[snippetName].push(line);

      inSnippetNames.push(snippetName);
    } else if (endMatch) {
      const snippetName = endMatch[1];
      config.map[snippetName].push(line);

      if (!inSnippetNames.includes(snippetName)) {
        throw new Error(
          `Unrecognized END tag ${snippetName} in ${filePath}.`
        );
      }
      inSnippetNames.splice(inSnippetNames.indexOf(snippetName), 1);
    } else if (inSnippetNames.length > 0) {
      for (const snippetName of inSnippetNames) {
        config.map[snippetName].push(line);
      }
    }
  }

  return config;
}

async function main() {
  const fileNames = listSnippetFiles();

  for (const filePath of fileNames) {
    const config = collectSnippets(filePath);
    if (!config.enabled) {
      continue;
    }

    const fileSlug = filePath
      .replace(".js", "")
      .replace("./", "")
      .replace(/\./g, "-");
    const snippetDir = path.join("./snippets", fileSlug);

    console.log(
      `Processing: ${filePath} --> ${snippetDir} (suffix=${config.suffix})`
    );

    if (!fs.existsSync(snippetDir)) {
      fs.mkdirSync(snippetDir, { recursive: true });
    }

    for (const snippetName in config.map) {
      const newFilePath = path.join(snippetDir, `${snippetName}.js`);
      const content = processSnippet(
        config.map[snippetName],
        filePath,
        config.suffix
      );
      fs.writeFileSync(newFilePath, content);
    }
  }
}

main();
