// This snippet file was generated by processing the source file:
// ./auth-react/email-link-auth.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START auth_email_link_link_react]
import { useActionState } from "react";
import { getAuth, linkWithCredential, EmailAuthProvider } from "firebase/auth";

function LinkEmailForm() {
  const [error, linkEmail, isPending] = useActionState(async (previousError, formData) => {
    // Construct the email link credential from the current URL.
    const credential = EmailAuthProvider.credentialWithLink(
      formData.get("email"), window.location.href);

    // Link the credential to the current user.
    const auth = getAuth();
    try {
      const usercred = await linkWithCredential(auth.currentUser, credential);
      // The provider is now successfully linked.
      // The phone user can now sign in with their phone number or email.
      return null;
    } catch (error) {
      // Some error occurred.
      return error.message;
    }
  }, null);

  return (
    <form action={linkEmail}>
      <input name="email" type="email" />
      <button type="submit" disabled={isPending}>Link email</button>
      {error ? <p>{error}</p> : null}
    </form>
  );
}
// [END auth_email_link_link_react]