// This snippet file was generated by processing the source file:
// ./auth-react/email-link-auth.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START auth_email_link_send_react]
import { useActionState } from "react";
import { getAuth, sendSignInLinkToEmail } from "firebase/auth";

function SendSignInLinkForm() {
  const [error, sendSignInLink, isPending] = useActionState(async (previousError, formData) => {
    const auth = getAuth();
    const email = formData.get("email");
    try {
      await sendSignInLinkToEmail(auth, email, actionCodeSettings);
      // The link was successfully sent. Inform the user.
      // Save the email locally so you don't need to ask the user for it again
      // if they open the link on the same device.
      window.localStorage.setItem('emailForSignIn', email);
      // ...
      return null;
    } catch (error) {
      const errorCode = error.code;
      const errorMessage = error.message;
      // ...
      return errorMessage;
    }
  }, null);

  return (
    <form action={sendSignInLink}>
      <input name="email" type="email" />
      <button type="submit" disabled={isPending}>Send sign-in link</button>
      {error ? <p>{error}</p> : null}
    </form>
  );
}
// [END auth_email_link_send_react]