// This snippet file was generated by processing the source file:
// ./database-react/lists-of-data.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START rtdb_social_most_viewed_react]
import { getDatabase, ref, query, orderByChild } from "firebase/database";

const db = getDatabase();
const mostViewedPosts = query(ref(db, 'posts'), orderByChild('metrics/views'));
// [END rtdb_social_most_viewed_react]