// This snippet file was generated by processing the source file:
// ./database-react/lists-of-data.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START rtdb_social_most_starred_react]
import { getDatabase, ref, query, orderByChild } from "firebase/database";
import { getAuth } from "firebase/auth";

const db = getDatabase();
const auth = getAuth();

const myUserId = auth.currentUser.uid;
const topUserPostsRef = query(ref(db, 'user-posts/' + myUserId), orderByChild('starCount'));
// [END rtdb_social_most_starred_react]