// This snippet file was generated by processing the source file:
// ./database-react/lists-of-data.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START rtdb_social_push_react]
import { getDatabase, ref, push, set } from "firebase/database";

function NewPostButton() {
  async function addPost() {
    // Create a new post reference with an auto-generated id
    const db = getDatabase();
    const postListRef = ref(db, 'posts');
    const newPostRef = push(postListRef);
    await set(newPostRef, {
        // ...
    });
  }

  return <button onClick={addPost}>New post</button>;
}
// [END rtdb_social_push_react]