// This snippet file was generated by processing the source file:
// ./storage-react/file-metadata.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START storage_update_metadata_react]
import { getStorage, ref, updateMetadata } from "firebase/storage";

function UpdateMetadataButton() {
  async function updateFileMetadata() {
    // Create a reference to the file whose metadata we want to change
    const storage = getStorage();
    const forestRef = ref(storage, 'images/forest.jpg');

    // Create file metadata to update
    const newMetadata = {
      cacheControl: 'public,max-age=300',
      contentType: 'image/jpeg'
    };

    // Update metadata properties
    try {
      const metadata = await updateMetadata(forestRef, newMetadata);
      // Updated metadata for 'images/forest.jpg' is returned in the Promise
    } catch (error) {
      // Uh-oh, an error occurred!
    }
  }

  return <button onClick={updateFileMetadata}>Update metadata</button>;
}
// [END storage_update_metadata_react]