// This snippet file was generated by processing the source file:
// ./storage-react/file-metadata.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START storage_get_metadata_react]
import { useEffect, useState } from "react";
import { getStorage, ref, getMetadata } from "firebase/storage";

function FileMetadata() {
  const [metadata, setMetadata] = useState(null);

  useEffect(() => {
    // Create a reference to the file whose metadata we want to retrieve
    const storage = getStorage();
    const forestRef = ref(storage, 'images/forest.jpg');

    // Get metadata properties
    getMetadata(forestRef)
      .then((metadata) => {
        // Metadata now contains the metadata for 'images/forest.jpg'
        setMetadata(metadata);
      })
      .catch((error) => {
        // Uh-oh, an error occurred!
      });
  }, []);

  return metadata ? <pre>{JSON.stringify(metadata, null, 2)}</pre> : <p>Loading...</p>;
}
// [END storage_get_metadata_react]