// This snippet file was generated by processing the source file:
// ./storage-react/file-metadata.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START storage_custom_metadata_react]
const metadata = {
  customMetadata: {
    'location': 'Yosemite, CA, USA',
    'activity': 'Hiking'
  }
};
// [END storage_custom_metadata_react]