// This snippet file was generated by processing the source file:
// ./auth-react/google-signin.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START auth_google_signin_credential_react]
signInWithCredential(auth, credential).catch((error) => {
  // Handle Errors here.
  const errorCode = error.code;
  const errorMessage = error.message;
  // The email of the user's account used.
  const email = error.customData.email;
  // The credential that was used.
  const credential = GoogleAuthProvider.credentialFromError(error);
  // ...
});
// [END auth_google_signin_credential_react]