// This snippet file was generated by processing the source file:
// ./auth-react/google-signin.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START auth_google_provider_credential_react]
import { GoogleAuthProvider } from "firebase/auth";

const credential = GoogleAuthProvider.credential(idToken);
// [END auth_google_provider_credential_react]