// This snippet file was generated by processing the source file:
// ./auth-react/google-signin.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START auth_google_provider_scopes_react]
provider.addScope('https://www.googleapis.com/auth/contacts.readonly');
// [END auth_google_provider_scopes_react]