// This snippet file was generated by processing the source file:
// ./auth-react/email.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START auth_send_password_reset_react]
import { useActionState } from "react";
import { getAuth, sendPasswordResetEmail } from "firebase/auth";

function PasswordResetForm() {
  const [error, sendPasswordReset, isPending] = useActionState(async (previousError, formData) => {
    const auth = getAuth();
    try {
      await sendPasswordResetEmail(auth, formData.get("email"));
      // Password reset email sent!
      // ..
      return null;
    } catch (error) {
      const errorCode = error.code;
      const errorMessage = error.message;
      // ..
      return errorMessage;
    }
  }, null);

  return (
    <form action={sendPasswordReset}>
      <input name="email" type="email" />
      <button type="submit" disabled={isPending}>Reset password</button>
      {error ? <p>{error}</p> : null}
    </form>
  );
}
// [END auth_send_password_reset_react]