// This snippet file was generated by processing the source file:
// ./firebaseapp-next/firebaseapp.js
//
// To make edits to the snippets in this file, please edit the source

// [START firebase_secondary_modular]
// Initialize another app with a different config
const secondaryApp = initializeApp(secondaryAppConfig, "secondary");
// Access services, such as the Realtime Database
// getDatabase(secondaryApp)
// [END firebase_secondary_modular]