// This snippet file was generated by processing the source file:
// ./firebaseapp-next/firebaseapp.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START firebase_options_modular]
import { initializeApp } from "firebase/app";

// The following fields are REQUIRED:
//  - Project ID
//  - App ID
//  - API Key
const secondaryAppConfig = {
    projectId: "<PROJECT_ID>",
    appId: "<APP_ID>",
    apiKey: "<API_KEY>",
    // databaseURL: "...",
    // storageBucket: "...",
};
// [END firebase_options_modular]