// This snippet file was generated by processing the source file:
// ./auth-react/yahoo-oauth.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START auth_yahoo_signin_redirect_react]
import { getAuth, signInWithRedirect } from "firebase/auth";

function SignInButton() {
  async function signIn() {
    const auth = getAuth();
    await signInWithRedirect(auth, provider);
  }

  return <button onClick={signIn}>Sign in with Yahoo</button>;
}
// [END auth_yahoo_signin_redirect_react]