// This snippet file was generated by processing the source file:
// ./storage-next/create-reference.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START storage_navigate_ref_chain_modular]
import { getStorage, ref } from "firebase/storage";

const storage = getStorage();
const spaceRef = ref(storage, 'images/space.jpg');

// References can be chained together multiple times
const earthRef = ref(spaceRef.parent, 'earth.jpg');
// earthRef points to 'images/earth.jpg'

// nullRef is null, since the parent of root is null
const nullRef = spaceRef.root.parent;
// [END storage_navigate_ref_chain_modular]