// This snippet file was generated by processing the source file:
// ./storage-next/create-reference.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START storage_create_ref_child_modular]
import { getStorage, ref } from "firebase/storage";

const storage = getStorage();

// Create a child reference
const imagesRef = ref(storage, 'images');
// imagesRef now points to 'images'

// Child references can also take paths delimited by '/'
const spaceRef = ref(storage, 'images/space.jpg');
// spaceRef now points to "images/space.jpg"
// imagesRef still points to "images"
// [END storage_create_ref_child_modular]