// This snippet file was generated by processing the source file:
// ./auth-next/google-signin.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START auth_google_callback_modular]
import { getAuth, onAuthStateChanged, signInWithCredential, GoogleAuthProvider } from "firebase/auth";
const auth = getAuth();

function onSignIn(googleResponse) {
  console.log('Sign in with Google response', googleResponse);
  // We need to register an Observer on Firebase Auth to make sure auth is initialized.
  const unsubscribe = onAuthStateChanged(auth, (firebaseUser) => {
    unsubscribe();
    // Build Firebase credential with the Google ID token.
    const googleIdToken = googleResponse.credential;
    const credential = GoogleAuthProvider.credential(googleIdToken);

    // Sign in with credential from the Google user.
    signInWithCredential(auth, credential).catch((error) => {
      // Handle Errors here.
      const errorCode = error.code;
      const errorMessage = error.message;
      // The email of the user's account used.
      const email = error.email;
      // The credential that was used.
      const credential = GoogleAuthProvider.credentialFromError(error);
      // ...
    });
  });
}
// [END auth_google_callback_modular]