// This snippet file was generated by processing the source file:
// ./auth-next/google-signin.js
//
// To make edits to the snippets in this file, please edit the source

// [START auth_google_provider_scopes_modular]
provider.addScope('https://www.googleapis.com/auth/contacts.readonly');
// [END auth_google_provider_scopes_modular]