// This snippet file was generated by processing the source file:
// ./firestore-next/test.pipelines.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START pipeline_join_multi_field_modular]
let results = await execute(db.pipeline()
  .collectionGroup("restaurants")
  .define(field("owner_id").as("owner_id"), field("__name__").as("__name__"))
  .where(db.pipeline()
    .collectionGroup("reviews")
    .where(field("restaurant").equal(variable("__name__")))
    .where(field("reviewer_id").equal(variable("owner_id")))
    .aggregate(countAll().as("c"))
    .toScalarExpression()
    .greaterThan(0)));
// [END pipeline_join_multi_field_modular]