// This snippet file was generated by processing the source file:
// ./firestore-next/test.pipelines.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START pipeline_join_uncorrelated_modular]
let results = await execute(db.pipeline()
  .collection("reviews")
  // Average review rating is 4.3
  .where(field("rating").greaterThan(db.pipeline()
    .collection("reviews")
    .aggregate(average("rating").as("avg"))
    .toScalarExpression()))
  .select("rating", "reviewer_id"));
// [END pipeline_join_uncorrelated_modular]