// This snippet file was generated by processing the source file:
// ./firestore-next/test.pipelines.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START pipeline_join_limit_modular]
let results = await execute(db.pipeline()
  .collectionGroup("restaurants")
  .define(field("__name__").as("restaurant_name"))
  .select(
    field("name"),
    db.pipeline()
      .collectionGroup("reviews")
      .where(field("restaurant").equal(variable("restaurant_name")))
      .sort(field("rating").descending())
      .limit(2)
      .select("rating", "reviewer_id")
      .toArrayExpression()
      .as("top_reviews")));
// [END pipeline_join_limit_modular]