// This snippet file was generated by processing the source file:
// ./firestore-next/test.pipelines.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START pipeline_join_lookup_modular]
let results = await execute(db.pipeline()
  .collectionGroup("reviews")
  .define(field("restaurant").as("restaurant_name"))
  .addFields(db.pipeline()
    .collectionGroup("restaurants")
    .where(field("__name__").equal(variable("restaurant_name")))
    .select("name", "type")
    .toScalarExpression()
    .as("restaurant")));
// [END pipeline_join_lookup_modular]