// This snippet file was generated by processing the source file:
// ./firestore-next/test.pipelines.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START pipeline_join_test_data_modular]
// Load set of cities.
const cities = collection(db, "cities");

await setDoc(doc(cities, "SF"), {
  name: "San Francisco",
  state: "CA",
  country: "USA",
});
await setDoc(doc(cities, "LA"), {
  name: "Los Angeles",
  state: "CA",
  country: "USA"
});
await setDoc(doc(cities, "DC"), {
  name: "Washington, D.C.",
  state: null,
  country: "USA"
});
await setDoc(doc(cities, "TOK"), {
  name: "Tokyo",
  state: null,
  country: "Japan"
});

// Load restaurants in various cities.
const sfRestaurants = collection(db, "cities", "SF", "restaurants");
const laRestaurants = collection(db, "cities", "LA", "restaurants");
const dcRestaurants = collection(db, "cities", "DC", "restaurants");

const rest1 = await addDoc(sfRestaurants, {
  name: "Golden Gate Pizza",
  type: "pizza",
  owner_id: "Mario Rossi"
});
const rest2 = await addDoc(sfRestaurants, {
  name: "Bay Area Burger",
  type: "burger",
  owner_id: "Sarah Jenkins"
});
const rest3 = await addDoc(sfRestaurants, {
  name: "Sunset Taco",
  type: "mexican",
  owner_id: "Edward"
});

const rest4 = await addDoc(laRestaurants, {
  name: "Hollywood Sushi",
  type: "sushi",
  owner_id: "Ken Kenji"
});
const rest5 = await addDoc(laRestaurants, {
  name: "Venice Pizza",
  type: "pizza",
  owner_id: "Luigi Romano"
});

const rest6 = await addDoc(dcRestaurants, {
  name: "Capitol Tacos",
  type: "mexican",
  owner_id: "Maria Garcia"
});
const rest7 = await addDoc(dcRestaurants, {
  name: "Georgetown Coffee",
  type: "cafe",
  owner_id: "David Kim"
});

// Load collection of reviews.
const reviews = collection(db, "reviews");

await addDoc(reviews, { restaurant: rest1, rating: 5, reviewer_id: "Alice" });
await addDoc(reviews, { restaurant: rest1, rating: 4, reviewer_id: "Bob" });
await addDoc(reviews, { restaurant: rest2, rating: 4, reviewer_id: "Charlie" });
await addDoc(reviews, { restaurant: rest3, rating: 5, reviewer_id: "Diana" });
await addDoc(reviews, { restaurant: rest3, rating: 4, reviewer_id: "Edward" });
await addDoc(reviews, { restaurant: rest3, rating: 4, reviewer_id: "Fiona" });
// rest4 has 0 reviews
await addDoc(reviews, { restaurant: rest5, rating: 3, reviewer_id: "George" });
await addDoc(reviews, { restaurant: rest6, rating: 5, reviewer_id: "Hannah" });
await addDoc(reviews, { restaurant: rest6, rating: 4, reviewer_id: "Ian" });
await addDoc(reviews, { restaurant: rest7, rating: 5, reviewer_id: "Julia" });
// [END pipeline_join_test_data_modular]