// This snippet file was generated by processing the source file:
// ./auth-next/link-multiple-accounts.js
//
// To make edits to the snippets in this file, please edit the source

// [START auth_simple_link_modular]
import { getAuth, linkWithCredential } from "firebase/auth";

const auth = getAuth(firebaseApp);
linkWithCredential(auth.currentUser, credential)
  .then((usercred) => {
    const user = usercred.user;
    console.log("Account linking success", user);
  }).catch((error) => {
    console.log("Account linking error", error);
  });
// [END auth_simple_link_modular]