// This snippet file was generated by processing the source file:
// ./auth-next/link-multiple-accounts.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START auth_merge_accounts_modular]
import { getAuth, signInWithCredential, deleteUser } from "firebase/auth";

// The implementation of how you store your user data depends on your application
const repo = new MyUserDataRepo();

// Get reference to the currently signed-in user
const auth = getAuth();
const prevUser = auth.currentUser;

// Get the data which you will want to merge. This should be done now
// while the app is still signed in as this user.
const prevUserData = repo.get(prevUser);

try {
  // Sign in user with the account you want to link to
  const result = await signInWithCredential(auth, newCredential);
  console.log("Sign In Success", result);
  const currentUser = result.user;
  const currentUserData = repo.get(currentUser);

  // Merge prevUser and currentUser data stored in Firebase.
  // Note: How you handle this is specific to your application
  const mergedData = repo.merge(prevUserData, currentUserData);

  // Save the merged data to the new user
  repo.set(currentUser, mergedData);

  // Delete the previous user's Firebase Auth account first
  await deleteUser(prevUser);
  repo.delete(prevUser);
} catch (error) {
  console.log("Sign In Error", error);
}
// [END auth_merge_accounts_modular]