// This snippet file was generated by processing the source file:
// ./auth-next/link-multiple-accounts.js
//
// To make edits to the snippets in this file, please edit the source

// [START auth_anonymous_link_modular]
import { getAuth, linkWithCredential } from "firebase/auth";

const auth = getAuth(firebaseApp);
linkWithCredential(auth.currentUser, credential)
  .then((usercred) => {
    const user = usercred.user;
    console.log("Anonymous account successfully upgraded", user);
  }).catch((error) => {
    console.log("Error upgrading anonymous account", error);
  });
// [END auth_anonymous_link_modular]