// This snippet file was generated by processing the source file:
// ./auth-react/manage.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START auth_reauth_with_credential_react]
import { useTransition } from "react";
import { getAuth, reauthenticateWithCredential } from "firebase/auth";

function ReauthenticateButton() {
  const [isPending, startTransition] = useTransition();

  function reauthenticate() {
    startTransition(async () => {
      const auth = getAuth();
      const user = auth.currentUser;

      // TODO(you): prompt the user to re-provide their sign-in credentials
      const credential = promptForCredentials();

      try {
        await reauthenticateWithCredential(user, credential);
        // User re-authenticated.
      } catch (error) {
        // An error ocurred
        // ...
      }
    });
  }

  return <button onClick={reauthenticate} disabled={isPending}>Reauthenticate</button>;
}
// [END auth_reauth_with_credential_react]