// This snippet file was generated by processing the source file:
// ./auth-react/manage.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START auth_delete_user_react]
import { useTransition } from "react";
import { getAuth, deleteUser } from "firebase/auth";

function DeleteUserButton() {
  const [isPending, startTransition] = useTransition();

  function deleteAccount() {
    startTransition(async () => {
      const auth = getAuth();
      const user = auth.currentUser;

      try {
        await deleteUser(user);
        // User deleted.
      } catch (error) {
        // An error ocurred
        // ...
      }
    });
  }

  return <button onClick={deleteAccount} disabled={isPending}>Delete</button>;
}
// [END auth_delete_user_react]