// This snippet file was generated by processing the source file:
// ./auth-react/manage.jsx
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START send_email_verification_react]
import { useTransition } from "react";
import { getAuth, sendEmailVerification } from "firebase/auth";

function VerifyEmailButton() {
  const [isPending, startTransition] = useTransition();

  function sendVerificationEmail() {
    startTransition(async () => {
      const auth = getAuth();
      const user = auth.currentUser;

      try {
        await sendEmailVerification(user);
        // Email sent.
      } catch (error) {
        // An error ocurred
        // ...
      }
    });
  }

  return <button onClick={sendVerificationEmail} disabled={isPending}>Verify email</button>;
}
// [END send_email_verification_react]