// This snippet file was generated by processing the source file:
// ./functions-next/emulator-suite.js
//
// To make edits to the snippets in this file, please edit the source

// [START fb_functions_emulator_connect_modular]
import { getApp } from "firebase/app";
import { getFunctions, connectFunctionsEmulator } from "firebase/functions";

const functions = getFunctions(getApp());
connectFunctionsEmulator(functions, "localhost", 5001);
// [END fb_functions_emulator_connect_modular]