// This snippet file was generated by processing the source file:
// snippets/functions-next/emulator-suite/functions_emulator_connect.js
//
// To make edits to the snippets in this file, please edit the source

// [START modular_functions_emulator_connect]
import { getApp } from "firebase/app";
import { getFunctions, useFunctionsEmulator } from  "firebase/functions";

const functions = getFunctions(getApp());
useFunctionsEmulator(functions, "http://localhost:5001");
// [END modular_functions_emulator_connect]