// This snippet file was generated by processing the source file:
// ./functions-next/emulator-suite.js
//
// To make edits to the snippets in this file, please edit the source

// [START modular_functions_emulator_connect]
import { app } from "firebase/app";
import { getFunctions, useFunctionsEmulator } from  "firebase/functions";

const functions = getFunctions(app());
useFunctionsEmulator(functions, "http://localhost:5001");
// [END modular_functions_emulator_connect]