// This snippet file was generated by processing the source file:
// ./functions-next/emulator-suite.js
//
// To make edits to the snippets in this file, please edit the source

// [START modular_functions_callable_call]
import { app } from "firebase/app";
import { getFunctions, httpsCallable } from  "firebase/functions";

const functions = getFunctions(app());
const addMessage = httpsCallable(functions, 'addMessage');

const result = await addMessage({ text: '<message text>'});
const sanitizedMessage = result.data.text;
// ...
// [END modular_functions_callable_call]