name: CI Tests

on:
  - pull_request
  - push

permissions:
  contents: read

env:
  CI: true

jobs:
  unit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 22.x
          - 24.x
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          persist-credentials: false
      - name: Install pnpm and Node.js
        uses: pnpm/setup@c9883cc79df532ad1a7b81bf9ab944ceb090d65c # v2.0.0
        with:
          runtime: node@${{ matrix.node-version }}
          cache: true
          cache-dependency-path: '**/package.json'

      - name: Lint snippets
        run: pnpm run lint

      - name: Compile snippets
        run: pnpm run compile

      - name: Check generated snippets
        run: |
          pnpm run snippets
          ./scripts/checkdirty.sh
