// This snippet file was generated by processing the source file:
// ./auth-next/apple.js
//
// To make edits to the snippets in this file, please edit the source

// [START auth_apple_provider_create_modular]
import { OAuthProvider } from "firebase/auth";

const provider = new OAuthProvider('apple.com');
// [END auth_apple_provider_create_modular]