// This snippet file was generated by processing the source file:
// ./auth-next/apple.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START auth_apple_provider_params_modular]
provider.setCustomParameters({
  // Localize the Apple authentication screen in French.
  locale: 'fr'
});
// [END auth_apple_provider_params_modular]