// This snippet file was generated by processing the source file:
// ./auth-next/apple.js
//
// To make edits to the snippets in this file, please edit the source

// [START auth_apple_provider_scopes_modular]
provider.addScope('email');
provider.addScope('name');
// [END auth_apple_provider_scopes_modular]