// This snippet file was generated by processing the source file:
// ./auth-next/apple.js
//
// To make edits to the snippets in this file, please edit the source

// [START auth_apple_signin_nonce_modular]
import { getAuth, signInWithCredential, OAuthProvider } from "firebase/auth";

const auth = getAuth(firebaseApp);

// Build Firebase credential with the Apple ID token.
const provider = new OAuthProvider('apple.com');
const authCredential = provider.credential({
  idToken: appleIdToken,
  rawNonce: unhashedNonce,
});

// Sign in with credential form the Apple user.
signInWithCredential(auth, authCredential)
  .then((result) => {
    // User signed in.
  })
  .catch((error) => {
    // An error occurred. If error.code == 'auth/missing-or-invalid-nonce',
    // make sure you're sending the SHA256-hashed nonce as a hex string
    // with your request to Apple.
    console.log(error);
  });
// [END auth_apple_signin_nonce_modular]