// This snippet file was generated by processing the source file:
// ./auth-next/apple.js
//
// To make edits to the snippets in this file, please edit the source

// [START auth_apple_link_facebook_modular]
import { getAuth, linkWithPopup, FacebookAuthProvider } from "firebase/auth";

const auth = getAuth(firebaseApp);
const provider = new FacebookAuthProvider();
provider.addScope('user_birthday');

// Assuming the current user is an Apple user linking a Facebook provider.
linkWithPopup(auth.currentUser, provider)
    .then((result) => {
      // Facebook credential is linked to the current Apple user.
      // ...

      // The user can now sign in to the same account
      // with either Apple or Facebook.
    })
    .catch((error) => {
      // Handle error.
    });
// [END auth_apple_link_facebook_modular]