// This snippet file was generated by processing the source file:
// ./auth-next/apple.js
//
// To make edits to the snippets in this file, please edit the source

// [START auth_apple_provider_params_modular]
provider.setCustomParameters({
  // Localize the Apple authentication screen in French.
  locale: 'fr'
});
// [END auth_apple_provider_params_modular]